#!/usr/bin/python

#modified on: 29-01-2015

import sys, os
sys.path.append('..')
from subprocess import call
from hopspack.configure import Configure, Comparing_Variable, TargetParameter
from parameter_set import BiomeBGCParameterSet
from application import ApplicationProperty
import glob
from hopspack.stat_ipt import stat
from copy import deepcopy
import random
import time
from multiprocessing import Process, Lock, Manager, Value

def write_output_file (out_filename, result_que, lock, stop_flag):
    file = None

    while not (stop_flag.value == 1 and result_que.empty()):
        if not result_que.empty():
            try:
                file = open(out_filename, "a")
                l = ''
                temp = result_que.get()
                for x in temp: l += str(x) + ';'
                file.write(l + '\n')
            except:
                lock.acquire()
                print("ERROR opening output file '%s'.\n" % out_filename)
                lock.release()
            finally:
                try: file.close()
                except: pass
        else: time.sleep(3)
    return 0

def clean_files(model_directory, prefix):
    file_list = []

    folder_list = ['ini', 'epc', 'soil', 'outputs']
    for folder in folder_list:
        file_list += glob.glob(os.path.join(model_directory, folder, '*' + prefix + '*.*'))

    for filename in file_list: 
        try: os.remove(filename)
        except: pass

def random_point_generation(parameter_list, number_of_random_point, hard_bound=False):
    #This function will generate random points for parameters. A random integer (m) in the range from zero to total number
    #of random points (n) will be generated by finding the reminder of n from a random integer devidend (d) having larger
    #range; i.e. m = d % n. step length (s) is calculated from the parameter value range (upper bound - lower bound) and
    #total number of points, n. Finally, the point will be calculated by adding the m times s with lower bound).
    #The function will return a list containing parameter point sets (ps) i.e. each point set is a list of values for all
    #parameters.

    random_point_list = []          #the list will parameter point sets

    n = number_of_random_point      #short notation for number of random points
    rr = n * 100000                 #large range for random number

    for p in parameter_list:
        u = p.upper_bound           #default upper bound
        l = p.lower_bound           #default lower bound

        if hard_bound:
            u = p.hard_upper_bound
            l = p.hard_lower_bound


        r = u - l                   #range = upper bound - lower bound
        s = r / n                   #step length, s = range / total no. of points

        for i in range(n):
            random.seed()
            d = random.randint(0, rr)

            x = l + (d % n) * s

            try: random_point_list[i].append(x)
            except: random_point_list.append([x])

    return random_point_list

def save_random_pointset(random_pointset, filename):
    f = None
    try:
        f = open(filename, 'a')
        for i in range(len(random_pointset)):
            l = str(i + 1)

            ps = random_pointset[i]
            for p in ps:
                l += ';' + str(p)

            f.write(l + '\n')
    except: return False
    finally:
        try: f.close()
        except: pass

    return True

def read_random_pointset(filename, parameter_count):
    random_pointset = []

    f = None
    try:
        f = open(filename, 'r')
        for line in f.readlines():
            temp = []
            for v in line.split(';')[1:]:
                try: temp.append(float(v))
                except: break
            if len(temp) == parameter_count: random_pointset.append(temp)
    except: pass
    finally:
        try: f.close()
        except: pass

    return random_pointset




def simulation_execution_and_evaluation(configuration_hp, bgc_parameter_set, parameter_point_set, param_map_list,
                                        comparison_map_list, run_number, result_que, thread_count):
    #checking if the number of parameter is equal to number of given values in parameter point set
    if len(parameter_point_set) != len(param_map_list): return False

    #updating current value for each parameter in parameter map list
    for i in range(len(param_map_list)): param_map_list[i].current_value = parameter_point_set[i]

    #reading current model directory
    bgc_directory = ApplicationProperty.currentModelDirectory

    #setting version number
    version_text = 'ipt_' + str(run_number)
    try:
        #changing the bgc model parameter values
        if bgc_parameter_set.vegParam is not None:
            if len(bgc_parameter_set.vegParam) == 1:
                site_index = bgc_parameter_set.vegParam[0]["siteIndex"]
                veg_id = bgc_parameter_set.vegParam[0]["vegid"]

                for param in param_map_list:
                    bgc_parameter_set.updateEpcObject(site_index, veg_id, -1, param.name, param.current_value,
                                                        version_text)

        #saving modified bgc model parameter set
        bgc_parameter_set.initParam.output_file_prefix += version_text
        initialization_filename = configuration_hp.initial_filename.replace('.ini', '_' + version_text + '.ini')
        BiomeBGCParameterSet.save_parameter_set(bgc_parameter_set, bgc_directory, initialization_filename, version_text)

        #execution of bgc model
        call(os.path.join(bgc_directory, "bgc_zalf.sh") + " " + initialization_filename + " y", shell=True)

        #evaluate model output
        norm_obs_max, norm_obs_mean = False, False
        if configuration_hp.normalization_option_flag == 0: norm_obs_max = True
        elif configuration_hp.normalization_option_flag == 1: norm_obs_mean = True

        fun_value_list = stat.data_evaluation(bgc_directory, initialization_filename, comparison_map_list,
                                             norm_obs_max, norm_obs_mean)

        temp = [configuration_hp.plot_no, Comparing_Variable.objective_function, run_number]
        result_que.put(temp + fun_value_list)

    except: return False
    finally:
        clean_files(bgc_directory, version_text)
        thread_count.value -= 1

    return True

def clean_process_list(process_list):
    for i in reversed(range(len(process_list))):
        p = process_list[i]
        if not p.is_alive(): process_list.pop(i)

    if len(process_list) == 0: return True
    else: return False


def main (argv):
    #step-1: reading system arguments

    #checking if appropriate number of arguments is given
    if len(argv) < 5:
        exit("usage: %s <model evaluation function> <plot number> <number of random walk> <number of thread/workers>" %argv[0])

    #declaring and initializing necessary variables
    mef = ''        #model evaluation function
    plot_no = ''    #plot number
    total_random_walk = 0   #number of random walk
    worker_number = 1   #number of thread

    #reading model evaluation function from system argument
    temp = argv[1].lower()
    if temp in ['mape', 'Mean Absolute Percentage Error']: mef = 'Mean Absolute Percentage Error'
    elif temp in ['ioa', 'index of agreement']: mef = 'Index of Agreement'
    elif temp in ['mae', 'mean absolute error']: mef = 'Mean Absolute Error'
    elif temp in ['mse', 'mean square error']: mef = 'Mean Square Error'
    elif temp in ['nse', 'nash-sutcliffe efficiency', 'nash sutcliffe efficiency']: mef = 'Nash-Sutcliffe Efficiency'
    elif temp in ['pbias', 'percentage bias']: mef = 'Percentage Bias'
    elif temp in ['r2', 'coefficient of determination']: mef = 'Coefficient of Determination'
    elif temp in ['rmse', 'root mean square error']: mef = 'Root Mean Square Error'
    elif temp in ['rsr', 'rmse-observed stdv. ratio']: mef = 'RMSE-Observed Stdv. Ratio'
    if mef == '': exit('Given model evaluation function is incorrect! Please try again.')

    #reading plot number from system argument
    plot_no = argv[2]
    if plot_no == '': exit('Plot number is blank. Please enter a plot number')

    #reading number of random walk from system argument
    try: temp = int(argv[3])
    except: temp = 0
    if temp > 0: total_random_walk = temp
    else: exit('Random number cannot be blank or less than 1. Please enter a valid number.')

    #reading thread number from system argument
    try: temp = int(argv[4])
    except: temp = 1
    if temp > 1: worker_number = temp

    #step-2: generation of random parameter points
    #notes: in order to generate random points, parameter list is required; thus, parameter-map file
    #must be read in. the address of parameter-map file can be read in from configuration file.

    #reading configuration file
    filename = 'config/start_value/configuration_' + plot_no + '.txt'
    config = None
    if os.path.exists(filename): config = Configure(filename)
    else: exit('Configuration file is not found!')
    config.objective_function = mef

    #reading parameter-map file
    param_map_list = []
    if config.parameterMap_file:
        if os.path.exists(config.parameterMap_file): TargetParameter.read_parameter_list(config.parameterMap_file, param_map_list)
        else: exit('Parameter-map file is not found!')
        if len(param_map_list) == 0: exit('Parameter-map file is either empty or is not properly written.')
    else: exit('No parameter-map file specified in configuration file. Please check configuration file.')

    #generating random points
    random_pointset = []
    #checking if random points are available in file
    filename = 'output/starting_point/random_pointset_' + plot_no + '_' + argv[1].lower() + '.txt'
    #if os.path.exists(filename): random_pointset = read_random_pointset(filename, len(param_map_list))

    if len(random_pointset) == 0 or len(random_pointset) != total_random_walk:
        random_pointset = random_point_generation(param_map_list, total_random_walk, hard_bound=False)
        #saving the points into file
        save_random_pointset(random_pointset, filename)

    #step-3: preparation for simulation run and evaluation

    #reading comparison-map file
    comparison_list = None
    Comparing_Variable.objective_function = config.objective_function
    if mef in ['Nash-Sutcliffe Efficiency','RMSE-Observed Stdv. Ratio', 'Coefficient of Determination']:
        config.comparisonMap_file = config.comparisonMap_file[:-4] + '_nse_rsr_r2.txt'
    if os.path.exists(config.comparisonMap_file): comparison_list = Comparing_Variable.read_comparing_variables(config.comparisonMap_file)
    else: exit('Comparison-map file could not be found.')
    if len(comparison_list) == 0: exit('Comparison file is either empty or does not follow proper format.')
    for comp_var in comparison_list: comp_var.objective_function = config.objective_function

    #setting bgc model working directory
    bgc_directory = config.model_directory
    initial_filename = os.path.join(bgc_directory, 'ini', config.initial_filename)
    ApplicationProperty.currentModelDirectory = bgc_directory

    #reading bgc model parameter set
    bgc_param = BiomeBGCParameterSet.ReadBBGCParameterSet(bgc_directory, initial_filename)

    #runing background process for result writing
    mgr = Manager()
    result_que = mgr.Queue()
    lock = Lock()
    stop_flag = Value('b', 0)
    filename = 'output/starting_point/ipt_' + plot_no + '.txt'
    wrp = Process(name='ipt_wr', target=write_output_file, args=(filename, result_que, lock, stop_flag))
    wrp.daemon = True
    wrp.start()

    #run bgc executions
    thread_count = Value('i', 0)
    config.plot_no = plot_no

    process_list = []
    point_counter = 0
    progress_report_ind = total_random_walk/10
    while point_counter < total_random_walk:
        clean_process_list(process_list)
        if thread_count.value < worker_number:


            ps = random_pointset[point_counter]

            p = Process(target=simulation_execution_and_evaluation, args=(config, deepcopy(bgc_param), ps, param_map_list,
                                                                          comparison_list, point_counter + 1, result_que,
                                                                          thread_count,))
            process_list.append(p)
            p.daemon = True
            p.start()

            if progress_report_ind:
                if (point_counter + 1)% progress_report_ind == 0:
                    lock.acquire()
                    print('\t%d %% completed' % (int((point_counter + 1)/progress_report_ind)*10))
                    lock.release()

            point_counter += 1
            thread_count.value += 1
        else: time.sleep(2)
    else:
        while not clean_process_list(process_list): time.sleep(2)
        else: stop_flag.value = 1

    wrp.join(120)

    
main(sys.argv)
