# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogGraphCompare.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogGraphCompare(object):
    def setupUi(self, DialogGraphCompare):
        DialogGraphCompare.setObjectName("DialogGraphCompare")
        DialogGraphCompare.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogGraphCompare.resize(862, 580)
        DialogGraphCompare.setMinimumSize(QtCore.QSize(860, 580))
        DialogGraphCompare.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(DialogGraphCompare)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(DialogGraphCompare)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioGraphCurrentVerion = QtWidgets.QRadioButton(self.widget)
        self.radioGraphCurrentVerion.setChecked(True)
        self.radioGraphCurrentVerion.setObjectName("radioGraphCurrentVerion")
        self.horizontalLayout_2.addWidget(self.radioGraphCurrentVerion)
        self.radioGraphsAllVersion = QtWidgets.QRadioButton(self.widget)
        self.radioGraphsAllVersion.setObjectName("radioGraphsAllVersion")
        self.horizontalLayout_2.addWidget(self.radioGraphsAllVersion)
        self.comboGraphName = QtWidgets.QComboBox(self.widget)
        self.comboGraphName.setMinimumSize(QtCore.QSize(200, 0))
        self.comboGraphName.setObjectName("comboGraphName")
        self.horizontalLayout_2.addWidget(self.comboGraphName)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.horizontalLayout_2.setStretch(3, 5)
        self.verticalLayout.addWidget(self.widget)
        self.scrollAreaGraph = QtWidgets.QScrollArea(self.frame)
        self.scrollAreaGraph.setAutoFillBackground(False)
        self.scrollAreaGraph.setStyleSheet("")
        self.scrollAreaGraph.setWidgetResizable(False)
        self.scrollAreaGraph.setObjectName("scrollAreaGraph")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 758, 445))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollAreaGraph.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollAreaGraph)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout.addWidget(self.frame_3)
        self.buttonClose = QtWidgets.QPushButton(self.frame_2)
        self.buttonClose.setObjectName("buttonClose")
        self.horizontalLayout.addWidget(self.buttonClose)
        self.horizontalLayout.setStretch(0, 5)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(1, 5)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(DialogGraphCompare)
        QtCore.QMetaObject.connectSlotsByName(DialogGraphCompare)

    def retranslateUi(self, DialogGraphCompare):
        _translate = QtCore.QCoreApplication.translate
        DialogGraphCompare.setWindowTitle(_translate("DialogGraphCompare", "Graph Compare"))
        self.radioGraphCurrentVerion.setText(_translate("DialogGraphCompare", "Show Graphs for Current Version"))
        self.radioGraphsAllVersion.setText(_translate("DialogGraphCompare", "Show Selected Graph for All Versions"))
        self.buttonClose.setText(_translate("DialogGraphCompare", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogGraphCompare = QtWidgets.QDialog()
    ui = Ui_DialogGraphCompare()
    ui.setupUi(DialogGraphCompare)
    DialogGraphCompare.show()
    sys.exit(app.exec_())
