# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogShowLog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogShowLog(object):
    def setupUi(self, DialogShowLog):
        DialogShowLog.setObjectName("DialogShowLog")
        DialogShowLog.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogShowLog.resize(723, 517)
        DialogShowLog.setMinimumSize(QtCore.QSize(723, 517))
        DialogShowLog.setMaximumSize(QtCore.QSize(723, 517))
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogShowLog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(DialogShowLog)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.frame = QtWidgets.QFrame(DialogShowLog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.buttonClose = QtWidgets.QPushButton(self.frame)
        self.buttonClose.setObjectName("buttonClose")
        self.horizontalLayout.addWidget(self.buttonClose)
        self.horizontalLayout.setStretch(0, 5)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(DialogShowLog)
        QtCore.QMetaObject.connectSlotsByName(DialogShowLog)

    def retranslateUi(self, DialogShowLog):
        _translate = QtCore.QCoreApplication.translate
        DialogShowLog.setWindowTitle(_translate("DialogShowLog", "Log"))
        self.buttonClose.setText(_translate("DialogShowLog", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogShowLog = QtWidgets.QDialog()
    ui = Ui_DialogShowLog()
    ui.setupUi(DialogShowLog)
    DialogShowLog.show()
    sys.exit(app.exec_())
