# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogSoilFileName.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSoilFileName(object):
    def setupUi(self, DialogSoilFileName):
        DialogSoilFileName.setObjectName("DialogSoilFileName")
        DialogSoilFileName.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogSoilFileName.resize(419, 180)
        self.gridLayout_3 = QtWidgets.QGridLayout(DialogSoilFileName)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frameSaveAs = QtWidgets.QFrame(DialogSoilFileName)
        self.frameSaveAs.setAutoFillBackground(True)
        self.frameSaveAs.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.frameSaveAs.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameSaveAs.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameSaveAs.setObjectName("frameSaveAs")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frameSaveAs)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBoxFileNames = QtWidgets.QGroupBox(self.frameSaveAs)
        self.groupBoxFileNames.setObjectName("groupBoxFileNames")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxFileNames)
        self.gridLayout.setObjectName("gridLayout")
        self.labelProfileSaveAsFileName = QtWidgets.QLabel(self.groupBoxFileNames)
        self.labelProfileSaveAsFileName.setObjectName("labelProfileSaveAsFileName")
        self.gridLayout.addWidget(self.labelProfileSaveAsFileName, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBoxFileNames)
        self.label.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.txtProfileSaveAsFileName = QtWidgets.QLineEdit(self.groupBoxFileNames)
        self.txtProfileSaveAsFileName.setObjectName("txtProfileSaveAsFileName")
        self.gridLayout.addWidget(self.txtProfileSaveAsFileName, 0, 2, 1, 1)
        self.labelHorizonSaveAsFileName = QtWidgets.QLabel(self.groupBoxFileNames)
        self.labelHorizonSaveAsFileName.setObjectName("labelHorizonSaveAsFileName")
        self.gridLayout.addWidget(self.labelHorizonSaveAsFileName, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBoxFileNames)
        self.label_2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.txtHorizonSaveAsFileName = QtWidgets.QLineEdit(self.groupBoxFileNames)
        self.txtHorizonSaveAsFileName.setObjectName("txtHorizonSaveAsFileName")
        self.gridLayout.addWidget(self.txtHorizonSaveAsFileName, 1, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxFileNames, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frameSaveAs)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonOk = QtWidgets.QPushButton(self.frame)
        self.buttonOk.setMinimumSize(QtCore.QSize(85, 27))
        self.buttonOk.setMaximumSize(QtCore.QSize(85, 27))
        self.buttonOk.setObjectName("buttonOk")
        self.gridLayout_2.addWidget(self.buttonOk, 0, 1, 1, 1)
        self.buttonCancel = QtWidgets.QPushButton(self.frame)
        self.buttonCancel.setMinimumSize(QtCore.QSize(85, 27))
        self.buttonCancel.setMaximumSize(QtCore.QSize(85, 27))
        self.buttonCancel.setObjectName("buttonCancel")
        self.gridLayout_2.addWidget(self.buttonCancel, 0, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frameSaveAs, 0, 0, 1, 1)

        self.retranslateUi(DialogSoilFileName)
        QtCore.QMetaObject.connectSlotsByName(DialogSoilFileName)

    def retranslateUi(self, DialogSoilFileName):
        _translate = QtCore.QCoreApplication.translate
        DialogSoilFileName.setWindowTitle(_translate("DialogSoilFileName", "Dialog"))
        self.groupBoxFileNames.setTitle(_translate("DialogSoilFileName", "Save As"))
        self.labelProfileSaveAsFileName.setText(_translate("DialogSoilFileName", "Soil Profile File Name"))
        self.label.setText(_translate("DialogSoilFileName", ":"))
        self.labelHorizonSaveAsFileName.setText(_translate("DialogSoilFileName", "Soil Horizon File Name"))
        self.label_2.setText(_translate("DialogSoilFileName", ":"))
        self.buttonOk.setText(_translate("DialogSoilFileName", "OK"))
        self.buttonCancel.setText(_translate("DialogSoilFileName", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogSoilFileName = QtWidgets.QDialog()
    ui = Ui_DialogSoilFileName()
    ui.setupUi(DialogSoilFileName)
    DialogSoilFileName.show()
    sys.exit(app.exec_())
