# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormShowGraph.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormShowGraph(object):
    def setupUi(self, FormShowGraph):
        FormShowGraph.setObjectName("FormShowGraph")
        FormShowGraph.resize(703, 539)
        FormShowGraph.setMinimumSize(QtCore.QSize(695, 487))
        self.gridLayout_3 = QtWidgets.QGridLayout(FormShowGraph)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_4 = QtWidgets.QFrame(FormShowGraph)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelDataSource = QtWidgets.QLabel(self.frame)
        self.labelDataSource.setObjectName("labelDataSource")
        self.verticalLayout_2.addWidget(self.labelDataSource)
        self.tableDataSource = QtWidgets.QTableWidget(self.frame)
        self.tableDataSource.setObjectName("tableDataSource")
        self.tableDataSource.setColumnCount(0)
        self.tableDataSource.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableDataSource)
        self.gridLayout_4.addWidget(self.frame, 1, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.tableTemplate = QtWidgets.QTableWidget(self.groupBox)
        self.tableTemplate.setObjectName("tableTemplate")
        self.tableTemplate.setColumnCount(0)
        self.tableTemplate.setRowCount(0)
        self.gridLayout.addWidget(self.tableTemplate, 0, 0, 1, 2)
        self.labelGraphTitle = QtWidgets.QLabel(self.groupBox)
        self.labelGraphTitle.setObjectName("labelGraphTitle")
        self.gridLayout.addWidget(self.labelGraphTitle, 1, 0, 1, 1)
        self.lineEditGraphTitle = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditGraphTitle.setReadOnly(True)
        self.lineEditGraphTitle.setObjectName("lineEditGraphTitle")
        self.gridLayout.addWidget(self.lineEditGraphTitle, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout.addWidget(self.frame_3)
        self.buttonSaveAsNewTemplate = QtWidgets.QPushButton(self.frame_2)
        self.buttonSaveAsNewTemplate.setObjectName("buttonSaveAsNewTemplate")
        self.horizontalLayout.addWidget(self.buttonSaveAsNewTemplate)
        self.buttonEditGraph = QtWidgets.QPushButton(self.frame_2)
        self.buttonEditGraph.setObjectName("buttonEditGraph")
        self.horizontalLayout.addWidget(self.buttonEditGraph)
        self.buttonShowGraph = QtWidgets.QPushButton(self.frame_2)
        self.buttonShowGraph.setObjectName("buttonShowGraph")
        self.horizontalLayout.addWidget(self.buttonShowGraph)
        self.buttonClose = QtWidgets.QPushButton(self.frame_2)
        self.buttonClose.setObjectName("buttonClose")
        self.horizontalLayout.addWidget(self.buttonClose)
        self.horizontalLayout.setStretch(0, 5)
        self.gridLayout_4.addWidget(self.frame_2, 2, 0, 1, 2)
        self.gridLayout_3.addWidget(self.frame_4, 0, 0, 1, 1)

        self.retranslateUi(FormShowGraph)
        QtCore.QMetaObject.connectSlotsByName(FormShowGraph)

    def retranslateUi(self, FormShowGraph):
        _translate = QtCore.QCoreApplication.translate
        FormShowGraph.setWindowTitle(_translate("FormShowGraph", "Show Graph"))
        self.groupBox_2.setTitle(_translate("FormShowGraph", "Preview"))
        self.labelDataSource.setText(_translate("FormShowGraph", "Change Data Source:"))
        self.groupBox.setTitle(_translate("FormShowGraph", "Predefined Graphs"))
        self.labelGraphTitle.setText(_translate("FormShowGraph", "Graph Title :"))
        self.buttonSaveAsNewTemplate.setText(_translate("FormShowGraph", "Save As New Template"))
        self.buttonEditGraph.setText(_translate("FormShowGraph", "Edit Graph"))
        self.buttonShowGraph.setText(_translate("FormShowGraph", "Show Graph"))
        self.buttonClose.setText(_translate("FormShowGraph", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormShowGraph = QtWidgets.QWidget()
    ui = Ui_FormShowGraph()
    ui.setupUi(FormShowGraph)
    FormShowGraph.show()
    sys.exit(app.exec_())
