# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormHopspackProblemDefinition.ui'
#
# Created: Fri Aug 28 14:22:30 2015
#      by: PyQt5 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FormProblemDefinition(object):
    def setupUi(self, FormProblemDefinition):
        FormProblemDefinition.setObjectName(_fromUtf8("FormProblemDefinition"))
        FormProblemDefinition.resize(810, 607)
        self.gridLayout_4 = QtGui.QGridLayout(FormProblemDefinition)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.widget = QtWidgets.QWidget(FormProblemDefinition)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout.addWidget(self.widget_2)
        self.buttonSave = QtGui.QPushButton(self.widget)
        self.buttonSave.setMinimumSize(QtCore.QSize(0, 27))
        self.buttonSave.setObjectName(_fromUtf8("buttonSave"))
        self.horizontalLayout.addWidget(self.buttonSave)
        self.buttonClose = QtGui.QPushButton(self.widget)
        self.buttonClose.setMinimumSize(QtCore.QSize(0, 27))
        self.buttonClose.setObjectName(_fromUtf8("buttonClose"))
        self.horizontalLayout.addWidget(self.buttonClose)
        self.horizontalLayout.setStretch(0, 5)
        self.gridLayout_4.addWidget(self.widget, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(FormProblemDefinition)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabProblemDefinition = QtWidgets.QWidget()
        self.tabProblemDefinition.setObjectName(_fromUtf8("tabProblemDefinition"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabProblemDefinition)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.frame = QtGui.QFrame(self.tabProblemDefinition)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_50 = QtGui.QLabel(self.frame)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_5.addWidget(self.label_50, 4, 0, 1, 1)
        self.lineEditInitialParamValue = QtGui.QLineEdit(self.frame)
        self.lineEditInitialParamValue.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEditInitialParamValue.setObjectName(_fromUtf8("lineEditInitialParamValue"))
        self.gridLayout_5.addWidget(self.lineEditInitialParamValue, 4, 3, 1, 2)
        self.label_55 = QtGui.QLabel(self.frame)
        self.label_55.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_5.addWidget(self.label_55, 4, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.frame)
        self.label_13.setMinimumSize(QtCore.QSize(120, 26))
        self.label_13.setMaximumSize(QtCore.QSize(120, 26))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_56 = QtGui.QLabel(self.frame)
        self.label_56.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_5.addWidget(self.label_56, 5, 2, 1, 1)
        self.lineEditLowerBounds = QtGui.QLineEdit(self.frame)
        self.lineEditLowerBounds.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEditLowerBounds.setObjectName(_fromUtf8("lineEditLowerBounds"))
        self.gridLayout_5.addWidget(self.lineEditLowerBounds, 3, 3, 1, 2)
        self.lineEditNoOfParameters = QtGui.QLineEdit(self.frame)
        self.lineEditNoOfParameters.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEditNoOfParameters.setObjectName(_fromUtf8("lineEditNoOfParameters"))
        self.gridLayout_5.addWidget(self.lineEditNoOfParameters, 1, 3, 1, 2)
        self.comboBoxOptimizationObjectiveType = QtGui.QComboBox(self.frame)
        self.comboBoxOptimizationObjectiveType.setMinimumSize(QtCore.QSize(150, 26))
        self.comboBoxOptimizationObjectiveType.setMaximumSize(QtCore.QSize(150, 26))
        self.comboBoxOptimizationObjectiveType.setObjectName(_fromUtf8("comboBoxOptimizationObjectiveType"))
        self.gridLayout_5.addWidget(self.comboBoxOptimizationObjectiveType, 6, 3, 1, 2)
        self.label_45 = QtGui.QLabel(self.frame)
        self.label_45.setMinimumSize(QtCore.QSize(120, 26))
        self.label_45.setMaximumSize(QtCore.QSize(120, 26))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_5.addWidget(self.label_45, 3, 0, 1, 1)
        self.lineEditInitFunValue = QtGui.QLineEdit(self.frame)
        self.lineEditInitFunValue.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEditInitFunValue.setObjectName(_fromUtf8("lineEditInitFunValue"))
        self.gridLayout_5.addWidget(self.lineEditInitFunValue, 5, 3, 1, 2)
        self.label_41 = QtGui.QLabel(self.frame)
        self.label_41.setMinimumSize(QtCore.QSize(120, 26))
        self.label_41.setMaximumSize(QtCore.QSize(120, 26))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_5.addWidget(self.label_41, 2, 0, 1, 1)
        self.label_46 = QtGui.QLabel(self.frame)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_5.addWidget(self.label_46, 5, 0, 1, 1)
        self.label_53 = QtGui.QLabel(self.frame)
        self.label_53.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_5.addWidget(self.label_53, 2, 2, 1, 1)
        self.label_52 = QtGui.QLabel(self.frame)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_5.addWidget(self.label_52, 3, 5, 1, 1)
        self.label_47 = QtGui.QLabel(self.frame)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_5.addWidget(self.label_47, 6, 0, 1, 1)
        self.label_48 = QtGui.QLabel(self.frame)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_5.addWidget(self.label_48, 7, 0, 1, 1)
        self.lineEditUpperBounds = QtGui.QLineEdit(self.frame)
        self.lineEditUpperBounds.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEditUpperBounds.setObjectName(_fromUtf8("lineEditUpperBounds"))
        self.gridLayout_5.addWidget(self.lineEditUpperBounds, 2, 3, 1, 2)
        self.label_58 = QtGui.QLabel(self.frame)
        self.label_58.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_5.addWidget(self.label_58, 7, 2, 1, 1)
        self.comboBoxProblemDisplayOption = QtGui.QComboBox(self.frame)
        self.comboBoxProblemDisplayOption.setMinimumSize(QtCore.QSize(150, 26))
        self.comboBoxProblemDisplayOption.setMaximumSize(QtCore.QSize(150, 26))
        self.comboBoxProblemDisplayOption.setObjectName(_fromUtf8("comboBoxProblemDisplayOption"))
        self.gridLayout_5.addWidget(self.comboBoxProblemDisplayOption, 7, 3, 1, 2)
        self.label_57 = QtGui.QLabel(self.frame)
        self.label_57.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_5.addWidget(self.label_57, 6, 2, 1, 1)
        self.label_39 = QtGui.QLabel(self.frame)
        self.label_39.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_5.addWidget(self.label_39, 1, 2, 1, 1)
        self.label_54 = QtGui.QLabel(self.frame)
        self.label_54.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_5.addWidget(self.label_54, 3, 2, 1, 1)
        self.labelParamFilename = QtGui.QLabel(self.frame)
        self.labelParamFilename.setObjectName(_fromUtf8("labelParamFilename"))
        self.gridLayout_5.addWidget(self.labelParamFilename, 0, 4, 1, 1)
        self.checkBoxExtractFromParamFile = QtGui.QCheckBox(self.frame)
        self.checkBoxExtractFromParamFile.setMinimumSize(QtCore.QSize(215, 27))
        self.checkBoxExtractFromParamFile.setMaximumSize(QtCore.QSize(215, 27))
        self.checkBoxExtractFromParamFile.setObjectName(_fromUtf8("checkBoxExtractFromParamFile"))
        self.gridLayout_5.addWidget(self.checkBoxExtractFromParamFile, 0, 0, 1, 1)
        self.label_51 = QtGui.QLabel(self.frame)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_5.addWidget(self.label_51, 2, 5, 1, 1)
        self.buttonChooseParamFile = QtGui.QPushButton(self.frame)
        self.buttonChooseParamFile.setMinimumSize(QtCore.QSize(0, 27))
        self.buttonChooseParamFile.setMaximumSize(QtCore.QSize(30, 27))
        self.buttonChooseParamFile.setObjectName(_fromUtf8("buttonChooseParamFile"))
        self.gridLayout_5.addWidget(self.buttonChooseParamFile, 0, 3, 1, 1)
        self.label_59 = QtGui.QLabel(self.frame)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_5.addWidget(self.label_59, 4, 5, 1, 1)
        self.label_60 = QtGui.QLabel(self.frame)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_5.addWidget(self.label_60, 5, 5, 1, 1)
        self.gridLayout_6.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_10 = QtGui.QFrame(self.tabProblemDefinition)
        self.frame_10.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.gridLayout_6.addWidget(self.frame_10, 1, 1, 2, 1)
        self.frame_2 = QtGui.QFrame(self.tabProblemDefinition)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_6.addWidget(self.frame_2, 2, 0, 1, 1)
        self.frame_9 = QtGui.QFrame(self.tabProblemDefinition)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_9)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.radioButtonNewDefinitionFile = QtGui.QRadioButton(self.frame_9)
        self.radioButtonNewDefinitionFile.setChecked(True)
        self.radioButtonNewDefinitionFile.setObjectName(_fromUtf8("radioButtonNewDefinitionFile"))
        self.gridLayout_9.addWidget(self.radioButtonNewDefinitionFile, 0, 0, 1, 1)
        self.radioButtonUpdateProblemDefinition = QtGui.QRadioButton(self.frame_9)
        self.radioButtonUpdateProblemDefinition.setObjectName(_fromUtf8("radioButtonUpdateProblemDefinition"))
        self.gridLayout_9.addWidget(self.radioButtonUpdateProblemDefinition, 0, 1, 1, 1)
        self.pushButtonChooseDefinitionFile = QtGui.QPushButton(self.frame_9)
        self.pushButtonChooseDefinitionFile.setMinimumSize(QtCore.QSize(30, 27))
        self.pushButtonChooseDefinitionFile.setMaximumSize(QtCore.QSize(27, 16777215))
        self.pushButtonChooseDefinitionFile.setObjectName(_fromUtf8("pushButtonChooseDefinitionFile"))
        self.gridLayout_9.addWidget(self.pushButtonChooseDefinitionFile, 0, 2, 1, 1)
        self.labelProblemDefinitionFile = QtGui.QLabel(self.frame_9)
        self.labelProblemDefinitionFile.setObjectName(_fromUtf8("labelProblemDefinitionFile"))
        self.gridLayout_9.addWidget(self.labelProblemDefinitionFile, 0, 4, 1, 1)
        self.gridLayout_9.setColumnMinimumWidth(4, 5)
        self.gridLayout_9.setColumnStretch(4, 5)
        self.gridLayout_6.addWidget(self.frame_9, 0, 0, 1, 2)
        self.gridLayout_6.setColumnMinimumWidth(1, 5)
        self.gridLayout_6.setRowMinimumHeight(2, 5)
        self.gridLayout_6.setColumnStretch(1, 5)
        self.gridLayout_6.setRowStretch(2, 5)
        self.tabWidget.addTab(self.tabProblemDefinition, _fromUtf8(""))
        self.tabEvaluator = QtWidgets.QWidget()
        self.tabEvaluator.setObjectName(_fromUtf8("tabEvaluator"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tabEvaluator)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.frame_3 = QtGui.QFrame(self.tabEvaluator)
        self.frame_3.setMinimumSize(QtCore.QSize(600, 280))
        self.frame_3.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.frame_6 = QtGui.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_3.setContentsMargins(9, 0, 0, 0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.radioButtonSaveIOYes = QtGui.QRadioButton(self.frame_6)
        self.radioButtonSaveIOYes.setObjectName(_fromUtf8("radioButtonSaveIOYes"))
        self.gridLayout_3.addWidget(self.radioButtonSaveIOYes, 0, 0, 1, 1)
        self.radioButtonSaveIONo = QtGui.QRadioButton(self.frame_6)
        self.radioButtonSaveIONo.setChecked(True)
        self.radioButtonSaveIONo.setObjectName(_fromUtf8("radioButtonSaveIONo"))
        self.gridLayout_3.addWidget(self.radioButtonSaveIONo, 0, 1, 1, 1)
        self.frame_7 = QtGui.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_3.addWidget(self.frame_7, 0, 2, 1, 1)
        self.gridLayout_3.setColumnMinimumWidth(2, 3)
        self.gridLayout_3.setColumnStretch(2, 3)
        self.gridLayout_8.addWidget(self.frame_6, 8, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_8.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_8.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.frame_3)
        self.label_11.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_8.addWidget(self.label_11, 9, 1, 2, 2)
        self.label_10 = QtGui.QLabel(self.frame_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_8.addWidget(self.label_10, 9, 0, 2, 1)
        self.label_12 = QtGui.QLabel(self.frame_3)
        self.label_12.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_8.addWidget(self.label_12, 8, 1, 1, 2)
        self.comboBoxEvaluatorType = QtGui.QComboBox(self.frame_3)
        self.comboBoxEvaluatorType.setMinimumSize(QtCore.QSize(0, 27))
        self.comboBoxEvaluatorType.setMaximumSize(QtCore.QSize(220, 16777215))
        self.comboBoxEvaluatorType.setObjectName(_fromUtf8("comboBoxEvaluatorType"))
        self.gridLayout_8.addWidget(self.comboBoxEvaluatorType, 0, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_8.addWidget(self.label_9, 8, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_8.addWidget(self.label_4, 1, 1, 1, 2)
        self.label_14 = QtGui.QLabel(self.frame_3)
        self.label_14.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_8.addWidget(self.label_14, 7, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_8.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_8.addWidget(self.label_2, 0, 1, 1, 2)
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_8.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditOutputPrefix = QtGui.QLineEdit(self.frame_3)
        self.lineEditOutputPrefix.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEditOutputPrefix.setObjectName(_fromUtf8("lineEditOutputPrefix"))
        self.gridLayout_8.addWidget(self.lineEditOutputPrefix, 7, 4, 1, 1)
        self.lineEditInputPrefix = QtGui.QLineEdit(self.frame_3)
        self.lineEditInputPrefix.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEditInputPrefix.setObjectName(_fromUtf8("lineEditInputPrefix"))
        self.gridLayout_8.addWidget(self.lineEditInputPrefix, 5, 4, 1, 1)
        self.frame_11 = QtGui.QFrame(self.frame_3)
        self.frame_11.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame_11)
        self.gridLayout_7.setContentsMargins(9, 0, 0, 0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.radioButtonDebugInfoYes = QtGui.QRadioButton(self.frame_11)
        self.radioButtonDebugInfoYes.setObjectName(_fromUtf8("radioButtonDebugInfoYes"))
        self.gridLayout_7.addWidget(self.radioButtonDebugInfoYes, 0, 0, 1, 1)
        self.radioButtonDebugInfoNo = QtGui.QRadioButton(self.frame_11)
        self.radioButtonDebugInfoNo.setChecked(True)
        self.radioButtonDebugInfoNo.setObjectName(_fromUtf8("radioButtonDebugInfoNo"))
        self.gridLayout_7.addWidget(self.radioButtonDebugInfoNo, 0, 1, 1, 1)
        self.frame_12 = QtGui.QFrame(self.frame_11)
        self.frame_12.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.gridLayout_7.addWidget(self.frame_12, 0, 2, 1, 1)
        self.gridLayout_7.setColumnMinimumWidth(2, 3)
        self.gridLayout_7.setColumnStretch(2, 3)
        self.gridLayout_8.addWidget(self.frame_11, 10, 4, 1, 1)
        self.label_15 = QtGui.QLabel(self.frame_3)
        self.label_15.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_8.addWidget(self.label_15, 5, 1, 1, 1)
        self.frame_4 = QtGui.QFrame(self.frame_3)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 55))
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout = QtGui.QGridLayout(self.frame_4)
        self.gridLayout.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEditEvaluatorFilename = QtGui.QLineEdit(self.frame_4)
        self.lineEditEvaluatorFilename.setObjectName(_fromUtf8("lineEditEvaluatorFilename"))
        self.gridLayout.addWidget(self.lineEditEvaluatorFilename, 0, 0, 1, 2)
        self.pushButtonChooseEvaluator = QtGui.QPushButton(self.frame_4)
        self.pushButtonChooseEvaluator.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButtonChooseEvaluator.setMaximumSize(QtCore.QSize(30, 27))
        self.pushButtonChooseEvaluator.setObjectName(_fromUtf8("pushButtonChooseEvaluator"))
        self.gridLayout.addWidget(self.pushButtonChooseEvaluator, 0, 2, 1, 1)
        self.checkBoxEvaluatorRelativeAddress = QtGui.QCheckBox(self.frame_4)
        self.checkBoxEvaluatorRelativeAddress.setObjectName(_fromUtf8("checkBoxEvaluatorRelativeAddress"))
        self.gridLayout.addWidget(self.checkBoxEvaluatorRelativeAddress, 1, 0, 1, 1)
        self.frame_5 = QtGui.QFrame(self.frame_4)
        self.frame_5.setMinimumSize(QtCore.QSize(10, 0))
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout.addWidget(self.frame_5, 1, 1, 1, 2)
        self.pushButtonEvaluatorReferenceDirectory = QtGui.QPushButton(self.frame_4)
        self.pushButtonEvaluatorReferenceDirectory.setMinimumSize(QtCore.QSize(100, 27))
        self.pushButtonEvaluatorReferenceDirectory.setMaximumSize(QtCore.QSize(100, 27))
        self.pushButtonEvaluatorReferenceDirectory.setObjectName(_fromUtf8("pushButtonEvaluatorReferenceDirectory"))
        self.gridLayout.addWidget(self.pushButtonEvaluatorReferenceDirectory, 2, 0, 1, 1)
        self.labelEvaluatorReferenceDirectory = QtGui.QLabel(self.frame_4)
        self.labelEvaluatorReferenceDirectory.setObjectName(_fromUtf8("labelEvaluatorReferenceDirectory"))
        self.gridLayout.addWidget(self.labelEvaluatorReferenceDirectory, 2, 1, 1, 2)
        self.gridLayout_8.addWidget(self.frame_4, 2, 0, 1, 6)
        self.lineEditFilePrecision = QtGui.QLineEdit(self.frame_3)
        self.lineEditFilePrecision.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEditFilePrecision.setObjectName(_fromUtf8("lineEditFilePrecision"))
        self.gridLayout_8.addWidget(self.lineEditFilePrecision, 4, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_8.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.frame_3)
        self.label_16.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_8.addWidget(self.label_16, 4, 1, 1, 1)
        self.gridLayout_10.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_13 = QtGui.QFrame(self.tabEvaluator)
        self.frame_13.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName(_fromUtf8("frame_13"))
        self.gridLayout_10.addWidget(self.frame_13, 0, 1, 2, 1)
        self.frame_14 = QtGui.QFrame(self.tabEvaluator)
        self.frame_14.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.gridLayout_10.addWidget(self.frame_14, 1, 0, 1, 1)
        self.gridLayout_10.setColumnMinimumWidth(1, 5)
        self.gridLayout_10.setRowMinimumHeight(1, 5)
        self.gridLayout_10.setColumnStretch(1, 5)
        self.gridLayout_10.setRowStretch(1, 5)
        self.tabWidget.addTab(self.tabEvaluator, _fromUtf8(""))
        self.tabMediatorCitizen = QtWidgets.QWidget()
        self.tabMediatorCitizen.setObjectName(_fromUtf8("tabMediatorCitizen"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tabMediatorCitizen)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.groupBox_15 = QtGui.QGroupBox(self.tabMediatorCitizen)
        self.groupBox_15.setMinimumSize(QtCore.QSize(600, 280))
        self.groupBox_15.setMaximumSize(QtCore.QSize(600, 16777215))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_15)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.frame_18 = QtGui.QFrame(self.groupBox_15)
        self.frame_18.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_18.setObjectName(_fromUtf8("frame_18"))
        self.gridLayout_11 = QtGui.QGridLayout(self.frame_18)
        self.gridLayout_11.setContentsMargins(9, 0, 0, 0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.radioButtonSynchronusYes = QtGui.QRadioButton(self.frame_18)
        self.radioButtonSynchronusYes.setObjectName(_fromUtf8("radioButtonSynchronusYes"))
        self.gridLayout_11.addWidget(self.radioButtonSynchronusYes, 0, 0, 1, 1)
        self.radioButtonSynchronousNo = QtGui.QRadioButton(self.frame_18)
        self.radioButtonSynchronousNo.setChecked(True)
        self.radioButtonSynchronousNo.setObjectName(_fromUtf8("radioButtonSynchronousNo"))
        self.gridLayout_11.addWidget(self.radioButtonSynchronousNo, 0, 1, 1, 1)
        self.frame_19 = QtGui.QFrame(self.frame_18)
        self.frame_19.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_19.setObjectName(_fromUtf8("frame_19"))
        self.gridLayout_11.addWidget(self.frame_19, 0, 2, 1, 1)
        self.gridLayout_11.setColumnMinimumWidth(2, 3)
        self.gridLayout_11.setColumnStretch(2, 3)
        self.gridLayout_12.addWidget(self.frame_18, 3, 4, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_15)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_12.addWidget(self.label_17, 0, 0, 1, 2)
        self.label_30 = QtGui.QLabel(self.groupBox_15)
        self.label_30.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_12.addWidget(self.label_30, 7, 2, 1, 1)
        self.comboBoxMediatorDisplayOption = QtGui.QComboBox(self.groupBox_15)
        self.comboBoxMediatorDisplayOption.setMinimumSize(QtCore.QSize(0, 27))
        self.comboBoxMediatorDisplayOption.setMaximumSize(QtCore.QSize(250, 16777215))
        self.comboBoxMediatorDisplayOption.setObjectName(_fromUtf8("comboBoxMediatorDisplayOption"))
        self.gridLayout_12.addWidget(self.comboBoxMediatorDisplayOption, 7, 4, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_15)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_12.addWidget(self.label_19, 1, 0, 1, 2)
        self.label_24 = QtGui.QLabel(self.groupBox_15)
        self.label_24.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_12.addWidget(self.label_24, 3, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_15)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_12.addWidget(self.label_28, 7, 0, 1, 2)
        self.lineEditNoOfCitizen = QtGui.QLineEdit(self.groupBox_15)
        self.lineEditNoOfCitizen.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEditNoOfCitizen.setReadOnly(True)
        self.lineEditNoOfCitizen.setObjectName(_fromUtf8("lineEditNoOfCitizen"))
        self.gridLayout_12.addWidget(self.lineEditNoOfCitizen, 0, 4, 1, 1)
        self.lineEditMaxEvaluation = QtGui.QLineEdit(self.groupBox_15)
        self.lineEditMaxEvaluation.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEditMaxEvaluation.setObjectName(_fromUtf8("lineEditMaxEvaluation"))
        self.gridLayout_12.addWidget(self.lineEditMaxEvaluation, 1, 4, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_15)
        self.label_20.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_12.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_15)
        self.label_22.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_12.addWidget(self.label_22, 2, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_15)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_12.addWidget(self.label_27, 6, 0, 1, 2)
        self.label_21 = QtGui.QLabel(self.groupBox_15)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_12.addWidget(self.label_21, 2, 0, 1, 2)
        self.label_23 = QtGui.QLabel(self.groupBox_15)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_12.addWidget(self.label_23, 3, 0, 1, 2)
        self.lineEditNoOfThread = QtGui.QLineEdit(self.groupBox_15)
        self.lineEditNoOfThread.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEditNoOfThread.setObjectName(_fromUtf8("lineEditNoOfThread"))
        self.gridLayout_12.addWidget(self.lineEditNoOfThread, 2, 4, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_15)
        self.label_18.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_12.addWidget(self.label_18, 1, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_15)
        self.label_29.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_12.addWidget(self.label_29, 6, 2, 1, 1)
        self.lineEditSolutionFilePrecision = QtGui.QLineEdit(self.groupBox_15)
        self.lineEditSolutionFilePrecision.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEditSolutionFilePrecision.setObjectName(_fromUtf8("lineEditSolutionFilePrecision"))
        self.gridLayout_12.addWidget(self.lineEditSolutionFilePrecision, 6, 4, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_15)
        self.label_26.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_12.addWidget(self.label_26, 4, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_15)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_12.addWidget(self.label_25, 4, 0, 1, 1)
        self.frame_16 = QtGui.QFrame(self.groupBox_15)
        self.frame_16.setFrameShape(QtGui.QFrame.Box)
        self.frame_16.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_16.setObjectName(_fromUtf8("frame_16"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_16)
        self.gridLayout_2.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButtonChooseSolutionFile = QtGui.QPushButton(self.frame_16)
        self.pushButtonChooseSolutionFile.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonChooseSolutionFile.setObjectName(_fromUtf8("pushButtonChooseSolutionFile"))
        self.gridLayout_2.addWidget(self.pushButtonChooseSolutionFile, 0, 2, 1, 1)
        self.checkBoxSolutionRelativeAddress = QtGui.QCheckBox(self.frame_16)
        self.checkBoxSolutionRelativeAddress.setObjectName(_fromUtf8("checkBoxSolutionRelativeAddress"))
        self.gridLayout_2.addWidget(self.checkBoxSolutionRelativeAddress, 1, 0, 1, 1)
        self.lineEditSolutionFile = QtGui.QLineEdit(self.frame_16)
        self.lineEditSolutionFile.setObjectName(_fromUtf8("lineEditSolutionFile"))
        self.gridLayout_2.addWidget(self.lineEditSolutionFile, 0, 0, 1, 2)
        self.labelSolutionFileRefDirectory = QtGui.QLabel(self.frame_16)
        self.labelSolutionFileRefDirectory.setObjectName(_fromUtf8("labelSolutionFileRefDirectory"))
        self.gridLayout_2.addWidget(self.labelSolutionFileRefDirectory, 2, 1, 1, 2)
        self.pushButtonSolutionFileRefDirectory = QtGui.QPushButton(self.frame_16)
        self.pushButtonSolutionFileRefDirectory.setMinimumSize(QtCore.QSize(100, 27))
        self.pushButtonSolutionFileRefDirectory.setMaximumSize(QtCore.QSize(100, 27))
        self.pushButtonSolutionFileRefDirectory.setObjectName(_fromUtf8("pushButtonSolutionFileRefDirectory"))
        self.gridLayout_2.addWidget(self.pushButtonSolutionFileRefDirectory, 2, 0, 1, 1)
        self.frame_17 = QtGui.QFrame(self.frame_16)
        self.frame_17.setMinimumSize(QtCore.QSize(10, 0))
        self.frame_17.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_17.setObjectName(_fromUtf8("frame_17"))
        self.gridLayout_2.addWidget(self.frame_17, 1, 1, 1, 2)
        self.gridLayout_12.addWidget(self.frame_16, 5, 0, 1, 5)
        self.gridLayout_15.addWidget(self.groupBox_15, 0, 0, 1, 1)
        self.frame_21 = QtGui.QFrame(self.tabMediatorCitizen)
        self.frame_21.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_21.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_21.setObjectName(_fromUtf8("frame_21"))
        self.gridLayout_15.addWidget(self.frame_21, 0, 1, 2, 1)
        self.groupBox_16 = QtGui.QGroupBox(self.tabMediatorCitizen)
        self.groupBox_16.setMinimumSize(QtCore.QSize(600, 0))
        self.groupBox_16.setMaximumSize(QtCore.QSize(600, 16777215))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox_16)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.frame_15 = QtGui.QFrame(self.groupBox_16)
        self.frame_15.setMinimumSize(QtCore.QSize(425, 0))
        self.frame_15.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_15.setObjectName(_fromUtf8("frame_15"))
        self.gridLayout_13 = QtGui.QGridLayout(self.frame_15)
        self.gridLayout_13.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_61 = QtGui.QLabel(self.frame_15)
        self.label_61.setMinimumSize(QtCore.QSize(120, 0))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_13.addWidget(self.label_61, 0, 0, 1, 1)
        self.label_43 = QtGui.QLabel(self.frame_15)
        self.label_43.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_13.addWidget(self.label_43, 0, 1, 1, 1)
        self.comboBoxCitizenType = QtGui.QComboBox(self.frame_15)
        self.comboBoxCitizenType.setMinimumSize(QtCore.QSize(250, 27))
        self.comboBoxCitizenType.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBoxCitizenType.setObjectName(_fromUtf8("comboBoxCitizenType"))
        self.gridLayout_13.addWidget(self.comboBoxCitizenType, 0, 2, 1, 1)
        self.label_44 = QtGui.QLabel(self.frame_15)
        self.label_44.setMinimumSize(QtCore.QSize(120, 0))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_13.addWidget(self.label_44, 1, 0, 1, 1)
        self.label_64 = QtGui.QLabel(self.frame_15)
        self.label_64.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_13.addWidget(self.label_64, 1, 1, 1, 1)
        self.lineEditStepTolerence = QtGui.QLineEdit(self.frame_15)
        self.lineEditStepTolerence.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEditStepTolerence.setObjectName(_fromUtf8("lineEditStepTolerence"))
        self.gridLayout_13.addWidget(self.lineEditStepTolerence, 1, 2, 1, 1)
        self.label_38 = QtGui.QLabel(self.frame_15)
        self.label_38.setMinimumSize(QtCore.QSize(120, 0))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_13.addWidget(self.label_38, 2, 0, 1, 1)
        self.label_34 = QtGui.QLabel(self.frame_15)
        self.label_34.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_13.addWidget(self.label_34, 2, 1, 1, 1)
        self.comboBoxCitizenDisplay = QtGui.QComboBox(self.frame_15)
        self.comboBoxCitizenDisplay.setMinimumSize(QtCore.QSize(250, 27))
        self.comboBoxCitizenDisplay.setMaximumSize(QtCore.QSize(250, 16777215))
        self.comboBoxCitizenDisplay.setObjectName(_fromUtf8("comboBoxCitizenDisplay"))
        self.gridLayout_13.addWidget(self.comboBoxCitizenDisplay, 2, 2, 1, 1)
        self.gridLayout_14.addWidget(self.frame_15, 0, 0, 1, 1)
        self.frame_20 = QtGui.QFrame(self.groupBox_16)
        self.frame_20.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_20.setObjectName(_fromUtf8("frame_20"))
        self.gridLayout_14.addWidget(self.frame_20, 0, 1, 1, 1)
        self.gridLayout_14.setColumnMinimumWidth(1, 2)
        self.gridLayout_14.setColumnStretch(1, 2)
        self.gridLayout_15.addWidget(self.groupBox_16, 1, 0, 1, 1)
        self.frame_22 = QtGui.QFrame(self.tabMediatorCitizen)
        self.frame_22.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_22.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_22.setObjectName(_fromUtf8("frame_22"))
        self.gridLayout_15.addWidget(self.frame_22, 2, 0, 1, 2)
        self.gridLayout_15.setColumnMinimumWidth(1, 5)
        self.gridLayout_15.setRowMinimumHeight(2, 5)
        self.gridLayout_15.setColumnStretch(1, 5)
        self.gridLayout_15.setRowStretch(2, 5)
        self.tabWidget.addTab(self.tabMediatorCitizen, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(FormProblemDefinition)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormProblemDefinition)

    def retranslateUi(self, FormProblemDefinition):
        FormProblemDefinition.setWindowTitle(_translate("FormProblemDefinition", "HOPSPACK Problem Definition", None))
        self.buttonSave.setText(_translate("FormProblemDefinition", "Save", None))
        self.buttonClose.setText(_translate("FormProblemDefinition", "Close", None))
        self.label_50.setText(_translate("FormProblemDefinition", "Initial Parameter Values", None))
        self.label_55.setText(_translate("FormProblemDefinition", ":", None))
        self.label_13.setText(_translate("FormProblemDefinition", "No. of Parameters *", None))
        self.label_56.setText(_translate("FormProblemDefinition", ":", None))
        self.label_45.setText(_translate("FormProblemDefinition", "Lower Bound(s)*", None))
        self.label_41.setText(_translate("FormProblemDefinition", "Upper Bound(s)*", None))
        self.label_46.setText(_translate("FormProblemDefinition", "Initial Function Values", None))
        self.label_53.setText(_translate("FormProblemDefinition", ":", None))
        self.label_52.setText(_translate("FormProblemDefinition", "[use Space as seperator]", None))
        self.label_47.setText(_translate("FormProblemDefinition", "Optimization Objective Type*", None))
        self.label_48.setText(_translate("FormProblemDefinition", "Display Option", None))
        self.label_58.setText(_translate("FormProblemDefinition", ":", None))
        self.label_57.setText(_translate("FormProblemDefinition", ":", None))
        self.label_39.setText(_translate("FormProblemDefinition", ":", None))
        self.label_54.setText(_translate("FormProblemDefinition", ":", None))
        self.labelParamFilename.setText(_translate("FormProblemDefinition", "(address of the parameter file)", None))
        self.checkBoxExtractFromParamFile.setText(_translate("FormProblemDefinition", "Extract values from a parameter file", None))
        self.label_51.setText(_translate("FormProblemDefinition", "[use Space as seperator]", None))
        self.buttonChooseParamFile.setText(_translate("FormProblemDefinition", "...", None))
        self.label_59.setText(_translate("FormProblemDefinition", "[use Space as seperator]", None))
        self.label_60.setText(_translate("FormProblemDefinition", "[use Space as seperator]", None))
        self.radioButtonNewDefinitionFile.setText(_translate("FormProblemDefinition", "New Problem Definition", None))
        self.radioButtonUpdateProblemDefinition.setText(_translate("FormProblemDefinition", "Update Problem Definition", None))
        self.pushButtonChooseDefinitionFile.setText(_translate("FormProblemDefinition", "...", None))
        self.labelProblemDefinitionFile.setText(_translate("FormProblemDefinition", "(Problem Definition Filename)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProblemDefinition), _translate("FormProblemDefinition", "Problem Definition", None))
        self.radioButtonSaveIOYes.setText(_translate("FormProblemDefinition", "Yes", None))
        self.radioButtonSaveIONo.setText(_translate("FormProblemDefinition", "No", None))
        self.label_8.setText(_translate("FormProblemDefinition", "Output Prefix", None))
        self.label_7.setText(_translate("FormProblemDefinition", "Input Prefix", None))
        self.label_11.setText(_translate("FormProblemDefinition", ":", None))
        self.label_10.setText(_translate("FormProblemDefinition", "Show Debug Info.", None))
        self.label_12.setText(_translate("FormProblemDefinition", ":", None))
        self.label_9.setText(_translate("FormProblemDefinition", "Save IO Files", None))
        self.label_4.setText(_translate("FormProblemDefinition", ":", None))
        self.label_14.setText(_translate("FormProblemDefinition", ":", None))
        self.label_3.setText(_translate("FormProblemDefinition", "Address of Evaluator*", None))
        self.label_2.setText(_translate("FormProblemDefinition", ":", None))
        self.label.setText(_translate("FormProblemDefinition", "Evaluator Type*", None))
        self.radioButtonDebugInfoYes.setText(_translate("FormProblemDefinition", "Yes", None))
        self.radioButtonDebugInfoNo.setText(_translate("FormProblemDefinition", "No", None))
        self.label_15.setText(_translate("FormProblemDefinition", ":", None))
        self.pushButtonChooseEvaluator.setText(_translate("FormProblemDefinition", "...", None))
        self.checkBoxEvaluatorRelativeAddress.setText(_translate("FormProblemDefinition", "Use relative address", None))
        self.pushButtonEvaluatorReferenceDirectory.setText(_translate("FormProblemDefinition", "Ref. Direcctory", None))
        self.labelEvaluatorReferenceDirectory.setText(_translate("FormProblemDefinition", "(reference directory)", None))
        self.label_5.setText(_translate("FormProblemDefinition", "File Precision", None))
        self.label_16.setText(_translate("FormProblemDefinition", ":", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEvaluator), _translate("FormProblemDefinition", "Evaluator", None))
        self.groupBox_15.setTitle(_translate("FormProblemDefinition", "Mediator", None))
        self.radioButtonSynchronusYes.setText(_translate("FormProblemDefinition", "Yes", None))
        self.radioButtonSynchronousNo.setText(_translate("FormProblemDefinition", "No", None))
        self.label_17.setText(_translate("FormProblemDefinition", "No. of Citizen*", None))
        self.label_30.setText(_translate("FormProblemDefinition", ":", None))
        self.label_19.setText(_translate("FormProblemDefinition", "Maximum Evaluation", None))
        self.label_24.setText(_translate("FormProblemDefinition", ":", None))
        self.label_28.setText(_translate("FormProblemDefinition", "Display Option", None))
        self.lineEditNoOfCitizen.setText(_translate("FormProblemDefinition", "1", None))
        self.label_20.setText(_translate("FormProblemDefinition", ":", None))
        self.label_22.setText(_translate("FormProblemDefinition", ":", None))
        self.label_27.setText(_translate("FormProblemDefinition", "Solution File Precision", None))
        self.label_21.setText(_translate("FormProblemDefinition", "No. of Thread", None))
        self.label_23.setText(_translate("FormProblemDefinition", "Synchronous Evaluations", None))
        self.label_18.setText(_translate("FormProblemDefinition", ":", None))
        self.label_29.setText(_translate("FormProblemDefinition", ":", None))
        self.label_26.setText(_translate("FormProblemDefinition", ":", None))
        self.label_25.setText(_translate("FormProblemDefinition", "Solution Filename", None))
        self.pushButtonChooseSolutionFile.setText(_translate("FormProblemDefinition", "...", None))
        self.checkBoxSolutionRelativeAddress.setText(_translate("FormProblemDefinition", "Use relative address", None))
        self.labelSolutionFileRefDirectory.setText(_translate("FormProblemDefinition", "(reference directory)", None))
        self.pushButtonSolutionFileRefDirectory.setText(_translate("FormProblemDefinition", "Ref. Direcctory", None))
        self.groupBox_16.setTitle(_translate("FormProblemDefinition", "Citizen GSS", None))
        self.label_61.setText(_translate("FormProblemDefinition", "Citizen Type*", None))
        self.label_43.setText(_translate("FormProblemDefinition", ":", None))
        self.label_44.setText(_translate("FormProblemDefinition", "Step Tolerance", None))
        self.label_64.setText(_translate("FormProblemDefinition", ":", None))
        self.label_38.setText(_translate("FormProblemDefinition", "Display Option", None))
        self.label_34.setText(_translate("FormProblemDefinition", ":", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMediatorCitizen), _translate("FormProblemDefinition", "Mediator and Citizen-GSS", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    FormProblemDefinition = QtWidgets.QWidget()
    ui = Ui_FormProblemDefinition()
    ui.setupUi(FormProblemDefinition)
    FormProblemDefinition.show()
    sys.exit(app.exec_())

