# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormInputPackage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormInputPackage(object):
    def setupUi(self, FormInputPackage):
        FormInputPackage.setObjectName("FormInputPackage")
        FormInputPackage.resize(550, 400)
        FormInputPackage.setMinimumSize(QtCore.QSize(550, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(FormInputPackage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(FormInputPackage)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.groupBox)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelInitialFile = QtWidgets.QLabel(self.frame_3)
        self.labelInitialFile.setObjectName("labelInitialFile")
        self.horizontalLayout_2.addWidget(self.labelInitialFile)
        self.lineEditInitialFile = QtWidgets.QLineEdit(self.frame_3)
        self.lineEditInitialFile.setObjectName("lineEditInitialFile")
        self.horizontalLayout_2.addWidget(self.lineEditInitialFile)
        self.pushButtonBrowse = QtWidgets.QPushButton(self.frame_3)
        self.pushButtonBrowse.setObjectName("pushButtonBrowse")
        self.horizontalLayout_2.addWidget(self.pushButtonBrowse)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.horizontalLayout_2.setStretch(3, 5)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout.addWidget(self.frame_4)
        self.pushButtonOk = QtWidgets.QPushButton(self.frame_2)
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.horizontalLayout.addWidget(self.pushButtonOk)
        self.horizontalLayout.setStretch(0, 5)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(FormInputPackage)
        QtCore.QMetaObject.connectSlotsByName(FormInputPackage)

    def retranslateUi(self, FormInputPackage):
        _translate = QtCore.QCoreApplication.translate
        FormInputPackage.setWindowTitle(_translate("FormInputPackage", "Input Package"))
        self.labelInitialFile.setText(_translate("FormInputPackage", "Initialization File   :"))
        self.pushButtonBrowse.setText(_translate("FormInputPackage", "browse.."))
        self.pushButtonOk.setText(_translate("FormInputPackage", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormInputPackage = QtWidgets.QWidget()
    ui = Ui_FormInputPackage()
    ui.setupUi(FormInputPackage)
    FormInputPackage.show()
    sys.exit(app.exec_())
