# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormEvaluatorConfiguration.ui'
#
# Created: Tue Aug 25 14:20:06 2015
#      by: PyQt5 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FormEvaluatorConfiguration(object):
    def setupUi(self, FormEvaluatorConfiguration):
        FormEvaluatorConfiguration.setObjectName(_fromUtf8("FormEvaluatorConfiguration"))
        FormEvaluatorConfiguration.resize(921, 742)
        self.gridLayout_4 = QtGui.QGridLayout(FormEvaluatorConfiguration)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.widget = QtWidgets.QWidget(FormEvaluatorConfiguration)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout.addWidget(self.widget_2)
        self.buttonSave = QtGui.QPushButton(self.widget)
        self.buttonSave.setObjectName(_fromUtf8("buttonSave"))
        self.horizontalLayout.addWidget(self.buttonSave)
        self.buttonClose = QtGui.QPushButton(self.widget)
        self.buttonClose.setObjectName(_fromUtf8("buttonClose"))
        self.horizontalLayout.addWidget(self.buttonClose)
        self.horizontalLayout.setStretch(0, 5)
        self.gridLayout_4.addWidget(self.widget, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(FormEvaluatorConfiguration)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabParameterSelection = QtWidgets.QWidget()
        self.tabParameterSelection.setObjectName(_fromUtf8("tabParameterSelection"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabParameterSelection)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame_2 = QtGui.QFrame(self.tabParameterSelection)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.labelNotes = QtGui.QLabel(self.frame_2)
        self.labelNotes.setObjectName(_fromUtf8("labelNotes"))
        self.gridLayout_6.addWidget(self.labelNotes, 0, 0, 1, 1)
        self.buttonLoadFromFile = QtGui.QPushButton(self.frame_2)
        self.buttonLoadFromFile.setMinimumSize(QtCore.QSize(100, 27))
        self.buttonLoadFromFile.setMaximumSize(QtCore.QSize(100, 27))
        self.buttonLoadFromFile.setObjectName(_fromUtf8("buttonLoadFromFile"))
        self.gridLayout_6.addWidget(self.buttonLoadFromFile, 0, 1, 1, 1)
        self.buttonAddToList = QtGui.QPushButton(self.frame_2)
        self.buttonAddToList.setMinimumSize(QtCore.QSize(100, 27))
        self.buttonAddToList.setMaximumSize(QtCore.QSize(100, 27))
        self.buttonAddToList.setObjectName(_fromUtf8("buttonAddToList"))
        self.gridLayout_6.addWidget(self.buttonAddToList, 0, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setLineWidth(1)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 1, 0, 1, 3)
        self.gridLayout_5.addWidget(self.frame_2, 3, 0, 1, 6)
        self.tableSelectedParameters = QtGui.QTableWidget(self.tabParameterSelection)
        self.tableSelectedParameters.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tableSelectedParameters.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableSelectedParameters.setObjectName(_fromUtf8("tableSelectedParameters"))
        self.tableSelectedParameters.setColumnCount(0)
        self.tableSelectedParameters.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableSelectedParameters, 4, 0, 1, 6)
        self.tableParameterSelection = QtGui.QTableWidget(self.tabParameterSelection)
        self.tableParameterSelection.setMinimumSize(QtCore.QSize(0, 300))
        self.tableParameterSelection.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableParameterSelection.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.tableParameterSelection.setObjectName(_fromUtf8("tableParameterSelection"))
        self.tableParameterSelection.setColumnCount(0)
        self.tableParameterSelection.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableParameterSelection, 1, 0, 1, 6)
        self.checkBoxSpecifyIndex = QtGui.QCheckBox(self.tabParameterSelection)
        self.checkBoxSpecifyIndex.setMinimumSize(QtCore.QSize(310, 0))
        self.checkBoxSpecifyIndex.setMaximumSize(QtCore.QSize(310, 16777215))
        self.checkBoxSpecifyIndex.setObjectName(_fromUtf8("checkBoxSpecifyIndex"))
        self.gridLayout_5.addWidget(self.checkBoxSpecifyIndex, 0, 4, 1, 1)
        self.comboBoxParameterType = QtGui.QComboBox(self.tabParameterSelection)
        self.comboBoxParameterType.setMinimumSize(QtCore.QSize(150, 26))
        self.comboBoxParameterType.setMaximumSize(QtCore.QSize(150, 26))
        self.comboBoxParameterType.setObjectName(_fromUtf8("comboBoxParameterType"))
        self.gridLayout_5.addWidget(self.comboBoxParameterType, 0, 1, 1, 1)
        self.pushButtonInitialFile = QtGui.QPushButton(self.tabParameterSelection)
        self.pushButtonInitialFile.setMinimumSize(QtCore.QSize(30, 26))
        self.pushButtonInitialFile.setMaximumSize(QtCore.QSize(30, 26))
        self.pushButtonInitialFile.setObjectName(_fromUtf8("pushButtonInitialFile"))
        self.gridLayout_5.addWidget(self.pushButtonInitialFile, 0, 5, 1, 1)
        self.label_4 = QtGui.QLabel(self.tabParameterSelection)
        self.label_4.setMinimumSize(QtCore.QSize(120, 26))
        self.label_4.setMaximumSize(QtCore.QSize(120, 26))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.frame = QtGui.QFrame(self.tabParameterSelection)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_5.addWidget(self.frame, 0, 2, 1, 1)
        self.checkBoxPreferred = QtGui.QCheckBox(self.tabParameterSelection)
        self.checkBoxPreferred.setMinimumSize(QtCore.QSize(215, 27))
        self.checkBoxPreferred.setMaximumSize(QtCore.QSize(215, 27))
        self.checkBoxPreferred.setObjectName(_fromUtf8("checkBoxPreferred"))
        self.gridLayout_5.addWidget(self.checkBoxPreferred, 0, 3, 1, 1)
        self.tabWidget.addTab(self.tabParameterSelection, _fromUtf8(""))
        self.tabComparisonOption = QtWidgets.QWidget()
        self.tabComparisonOption.setObjectName(_fromUtf8("tabComparisonOption"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabComparisonOption)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame_4 = QtGui.QFrame(self.tabComparisonOption)
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tableComparisonOption = QtGui.QTableWidget(self.frame_4)
        self.tableComparisonOption.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableComparisonOption.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableComparisonOption.setObjectName(_fromUtf8("tableComparisonOption"))
        self.tableComparisonOption.setColumnCount(0)
        self.tableComparisonOption.setRowCount(0)
        self.gridLayout_8.addWidget(self.tableComparisonOption, 1, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.frame_4)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.buttonAddComparisonOption = QtGui.QPushButton(self.widget_6)
        self.buttonAddComparisonOption.setMinimumSize(QtCore.QSize(100, 27))
        self.buttonAddComparisonOption.setMaximumSize(QtCore.QSize(100, 27))
        self.buttonAddComparisonOption.setObjectName(_fromUtf8("buttonAddComparisonOption"))
        self.horizontalLayout_3.addWidget(self.buttonAddComparisonOption)
        self.buttonLoad = QtGui.QPushButton(self.widget_6)
        self.buttonLoad.setMinimumSize(QtCore.QSize(100, 27))
        self.buttonLoad.setMaximumSize(QtCore.QSize(100, 27))
        self.buttonLoad.setObjectName(_fromUtf8("buttonLoad"))
        self.horizontalLayout_3.addWidget(self.buttonLoad)
        self.widget_7 = QtWidgets.QWidget(self.widget_6)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.horizontalLayout_3.addWidget(self.widget_7)
        self.horizontalLayout_3.setStretch(2, 5)
        self.gridLayout_8.addWidget(self.widget_6, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_4, 1, 1, 1, 1)
        self.frame_3 = QtGui.QFrame(self.tabComparisonOption)
        self.frame_3.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout = QtGui.QGridLayout(self.frame_3)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEditMeasuredDataFile = QtGui.QLineEdit(self.frame_3)
        self.lineEditMeasuredDataFile.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEditMeasuredDataFile.setMaximumSize(QtCore.QSize(16777215, 27))
        self.lineEditMeasuredDataFile.setReadOnly(True)
        self.lineEditMeasuredDataFile.setObjectName(_fromUtf8("lineEditMeasuredDataFile"))
        self.gridLayout.addWidget(self.lineEditMeasuredDataFile, 8, 0, 1, 4)
        self.labelObservationDataFile = QtGui.QLabel(self.frame_3)
        self.labelObservationDataFile.setMinimumSize(QtCore.QSize(120, 0))
        self.labelObservationDataFile.setObjectName(_fromUtf8("labelObservationDataFile"))
        self.gridLayout.addWidget(self.labelObservationDataFile, 7, 0, 1, 5)
        self.label_22 = QtGui.QLabel(self.frame_3)
        self.label_22.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 2, 1, 1, 1)
        self.buttonMeasuredDataFile = QtGui.QPushButton(self.frame_3)
        self.buttonMeasuredDataFile.setMinimumSize(QtCore.QSize(30, 27))
        self.buttonMeasuredDataFile.setMaximumSize(QtCore.QSize(30, 27))
        self.buttonMeasuredDataFile.setObjectName(_fromUtf8("buttonMeasuredDataFile"))
        self.gridLayout.addWidget(self.buttonMeasuredDataFile, 8, 4, 1, 1)
        self.comboOutputFileType = QtGui.QComboBox(self.frame_3)
        self.comboOutputFileType.setMinimumSize(QtCore.QSize(0, 27))
        self.comboOutputFileType.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboOutputFileType.setObjectName(_fromUtf8("comboOutputFileType"))
        self.gridLayout.addWidget(self.comboOutputFileType, 2, 2, 1, 3)
        self.listOutputVariable = QtGui.QListWidget(self.frame_3)
        self.listOutputVariable.setObjectName(_fromUtf8("listOutputVariable"))
        self.gridLayout.addWidget(self.listOutputVariable, 3, 0, 1, 5)
        self.lineEditInitializationFile = QtGui.QLineEdit(self.frame_3)
        self.lineEditInitializationFile.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEditInitializationFile.setMaximumSize(QtCore.QSize(16777215, 27))
        self.lineEditInitializationFile.setReadOnly(True)
        self.lineEditInitializationFile.setObjectName(_fromUtf8("lineEditInitializationFile"))
        self.gridLayout.addWidget(self.lineEditInitializationFile, 1, 0, 1, 4)
        self.listMeasuredVariable = QtGui.QListWidget(self.frame_3)
        self.listMeasuredVariable.setObjectName(_fromUtf8("listMeasuredVariable"))
        self.gridLayout.addWidget(self.listMeasuredVariable, 9, 0, 1, 5)
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 5)
        self.buttonInitializationFile = QtGui.QPushButton(self.frame_3)
        self.buttonInitializationFile.setMinimumSize(QtCore.QSize(30, 27))
        self.buttonInitializationFile.setMaximumSize(QtCore.QSize(30, 27))
        self.buttonInitializationFile.setObjectName(_fromUtf8("buttonInitializationFile"))
        self.gridLayout.addWidget(self.buttonInitializationFile, 1, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.frame_3)
        self.label_21.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 5, 1, 1, 1)
        self.comboObservationDataType = QtGui.QComboBox(self.frame_3)
        self.comboObservationDataType.setMinimumSize(QtCore.QSize(0, 27))
        self.comboObservationDataType.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboObservationDataType.setObjectName(_fromUtf8("comboObservationDataType"))
        self.gridLayout.addWidget(self.comboObservationDataType, 5, 2, 1, 3)
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 2, 1)
        self.frame_5 = QtGui.QFrame(self.tabComparisonOption)
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lineEditMeasuredPairingVariable = QtGui.QLineEdit(self.frame_5)
        self.lineEditMeasuredPairingVariable.setMaximumSize(QtCore.QSize(234, 27))
        self.lineEditMeasuredPairingVariable.setReadOnly(True)
        self.lineEditMeasuredPairingVariable.setObjectName(_fromUtf8("lineEditMeasuredPairingVariable"))
        self.gridLayout_3.addWidget(self.lineEditMeasuredPairingVariable, 3, 5, 1, 3)
        self.label_15 = QtGui.QLabel(self.frame_5)
        self.label_15.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 6, 2, 1, 1)
        self.lineEditModelPairingVariable = QtGui.QLineEdit(self.frame_5)
        self.lineEditModelPairingVariable.setMinimumSize(QtCore.QSize(234, 27))
        self.lineEditModelPairingVariable.setMaximumSize(QtCore.QSize(234, 27))
        self.lineEditModelPairingVariable.setReadOnly(True)
        self.lineEditModelPairingVariable.setObjectName(_fromUtf8("lineEditModelPairingVariable"))
        self.gridLayout_3.addWidget(self.lineEditModelPairingVariable, 3, 1, 1, 3)
        self.buttonModelOutputVariable = QtGui.QPushButton(self.frame_5)
        self.buttonModelOutputVariable.setMinimumSize(QtCore.QSize(30, 27))
        self.buttonModelOutputVariable.setMaximumSize(QtCore.QSize(30, 27))
        self.buttonModelOutputVariable.setObjectName(_fromUtf8("buttonModelOutputVariable"))
        self.gridLayout_3.addWidget(self.buttonModelOutputVariable, 1, 0, 1, 1)
        self.lineEditWeighingFactor = QtGui.QLineEdit(self.frame_5)
        self.lineEditWeighingFactor.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEditWeighingFactor.setMaximumSize(QtCore.QSize(27, 16777215))
        self.lineEditWeighingFactor.setObjectName(_fromUtf8("lineEditWeighingFactor"))
        self.gridLayout_3.addWidget(self.lineEditWeighingFactor, 5, 3, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.frame_5)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_10.setObjectName(_fromUtf8("widget_10"))
        self.gridLayout_3.addWidget(self.widget_10, 0, 8, 10, 1)
        self.label_16 = QtGui.QLabel(self.frame_5)
        self.label_16.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 5, 2, 1, 1)
        self.buttonModelPairingVariable = QtGui.QPushButton(self.frame_5)
        self.buttonModelPairingVariable.setMinimumSize(QtCore.QSize(30, 27))
        self.buttonModelPairingVariable.setMaximumSize(QtCore.QSize(30, 27))
        self.buttonModelPairingVariable.setObjectName(_fromUtf8("buttonModelPairingVariable"))
        self.gridLayout_3.addWidget(self.buttonModelPairingVariable, 3, 0, 1, 1)
        self.buttonMeasuredPairingVariable = QtGui.QPushButton(self.frame_5)
        self.buttonMeasuredPairingVariable.setMinimumSize(QtCore.QSize(30, 27))
        self.buttonMeasuredPairingVariable.setMaximumSize(QtCore.QSize(30, 27))
        self.buttonMeasuredPairingVariable.setObjectName(_fromUtf8("buttonMeasuredPairingVariable"))
        self.gridLayout_3.addWidget(self.buttonMeasuredPairingVariable, 3, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 2)
        self.label_7 = QtGui.QLabel(self.frame_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 2, 4, 1, 4)
        self.lineEditModelVariableConversionFactor = QtGui.QLineEdit(self.frame_5)
        self.lineEditModelVariableConversionFactor.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEditModelVariableConversionFactor.setMaximumSize(QtCore.QSize(100, 27))
        self.lineEditModelVariableConversionFactor.setObjectName(_fromUtf8("lineEditModelVariableConversionFactor"))
        self.gridLayout_3.addWidget(self.lineEditModelVariableConversionFactor, 4, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.frame_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 5, 0, 1, 2)
        self.buttonMeasuredVariable = QtGui.QPushButton(self.frame_5)
        self.buttonMeasuredVariable.setMinimumSize(QtCore.QSize(30, 27))
        self.buttonMeasuredVariable.setMaximumSize(QtCore.QSize(30, 27))
        self.buttonMeasuredVariable.setObjectName(_fromUtf8("buttonMeasuredVariable"))
        self.gridLayout_3.addWidget(self.buttonMeasuredVariable, 1, 4, 1, 1)
        self.label_17 = QtGui.QLabel(self.frame_5)
        self.label_17.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 4, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 4, 0, 1, 2)
        self.checkBoxOverrideObjFun = QtGui.QCheckBox(self.frame_5)
        self.checkBoxOverrideObjFun.setMinimumSize(QtCore.QSize(0, 27))
        self.checkBoxOverrideObjFun.setMaximumSize(QtCore.QSize(16777215, 27))
        self.checkBoxOverrideObjFun.setObjectName(_fromUtf8("checkBoxOverrideObjFun"))
        self.gridLayout_3.addWidget(self.checkBoxOverrideObjFun, 8, 0, 2, 4)
        self.label_18 = QtGui.QLabel(self.frame_5)
        self.label_18.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 4, 6, 1, 1)
        self.lineEditModelOutputVariable = QtGui.QLineEdit(self.frame_5)
        self.lineEditModelOutputVariable.setMinimumSize(QtCore.QSize(234, 27))
        self.lineEditModelOutputVariable.setMaximumSize(QtCore.QSize(234, 27))
        self.lineEditModelOutputVariable.setReadOnly(True)
        self.lineEditModelOutputVariable.setObjectName(_fromUtf8("lineEditModelOutputVariable"))
        self.gridLayout_3.addWidget(self.lineEditModelOutputVariable, 1, 1, 1, 3)
        self.label_10 = QtGui.QLabel(self.frame_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 4, 4, 1, 2)
        self.lineEditMeasuredVariable = QtGui.QLineEdit(self.frame_5)
        self.lineEditMeasuredVariable.setMaximumSize(QtCore.QSize(234, 27))
        self.lineEditMeasuredVariable.setReadOnly(True)
        self.lineEditMeasuredVariable.setObjectName(_fromUtf8("lineEditMeasuredVariable"))
        self.gridLayout_3.addWidget(self.lineEditMeasuredVariable, 1, 5, 1, 3)
        self.label_14 = QtGui.QLabel(self.frame_5)
        self.label_14.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 6, 0, 1, 2)
        self.lineEditMeasuredVariableConversionFactor = QtGui.QLineEdit(self.frame_5)
        self.lineEditMeasuredVariableConversionFactor.setMinimumSize(QtCore.QSize(118, 27))
        self.lineEditMeasuredVariableConversionFactor.setMaximumSize(QtCore.QSize(118, 27))
        self.lineEditMeasuredVariableConversionFactor.setObjectName(_fromUtf8("lineEditMeasuredVariableConversionFactor"))
        self.gridLayout_3.addWidget(self.lineEditMeasuredVariableConversionFactor, 4, 7, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 4)
        self.label_6 = QtGui.QLabel(self.frame_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 4, 1, 4)
        self.comboCostFunction = QtGui.QComboBox(self.frame_5)
        self.comboCostFunction.setMinimumSize(QtCore.QSize(118, 27))
        self.comboCostFunction.setObjectName(_fromUtf8("comboCostFunction"))
        self.gridLayout_3.addWidget(self.comboCostFunction, 8, 4, 1, 4)
        self.lineEditGroupName = QtGui.QLineEdit(self.frame_5)
        self.lineEditGroupName.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEditGroupName.setObjectName(_fromUtf8("lineEditGroupName"))
        self.gridLayout_3.addWidget(self.lineEditGroupName, 6, 3, 1, 5)
        self.gridLayout_3.setColumnMinimumWidth(8, 5)
        self.gridLayout_3.setColumnStretch(8, 5)
        self.gridLayout_2.addWidget(self.frame_5, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tabComparisonOption, _fromUtf8(""))
        self.tabConfigurationOption = QtWidgets.QWidget()
        self.tabConfigurationOption.setObjectName(_fromUtf8("tabConfigurationOption"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tabConfigurationOption)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.frame_7 = QtGui.QFrame(self.tabConfigurationOption)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_10 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.radioButtonCreateConfigFile = QtGui.QRadioButton(self.frame_7)
        self.radioButtonCreateConfigFile.setChecked(True)
        self.radioButtonCreateConfigFile.setObjectName(_fromUtf8("radioButtonCreateConfigFile"))
        self.gridLayout_10.addWidget(self.radioButtonCreateConfigFile, 0, 0, 1, 1)
        self.radioButtonUpdateConfigFile = QtGui.QRadioButton(self.frame_7)
        self.radioButtonUpdateConfigFile.setObjectName(_fromUtf8("radioButtonUpdateConfigFile"))
        self.gridLayout_10.addWidget(self.radioButtonUpdateConfigFile, 0, 1, 1, 1)
        self.buttonChooseConfigFile = QtGui.QPushButton(self.frame_7)
        self.buttonChooseConfigFile.setMinimumSize(QtCore.QSize(120, 27))
        self.buttonChooseConfigFile.setMaximumSize(QtCore.QSize(120, 27))
        self.buttonChooseConfigFile.setObjectName(_fromUtf8("buttonChooseConfigFile"))
        self.gridLayout_10.addWidget(self.buttonChooseConfigFile, 0, 2, 1, 1)
        self.labelSelectedConfigFile = QtGui.QLabel(self.frame_7)
        self.labelSelectedConfigFile.setObjectName(_fromUtf8("labelSelectedConfigFile"))
        self.gridLayout_10.addWidget(self.labelSelectedConfigFile, 0, 3, 1, 1)
        self.gridLayout_10.setColumnMinimumWidth(3, 5)
        self.gridLayout_10.setColumnStretch(3, 5)
        self.gridLayout_9.addWidget(self.frame_7, 0, 0, 1, 2)
        self.frame_8 = QtGui.QFrame(self.tabConfigurationOption)
        self.frame_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.gridLayout_9.addWidget(self.frame_8, 1, 1, 1, 1)
        self.frame_9 = QtGui.QFrame(self.tabConfigurationOption)
        self.frame_9.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.gridLayout_9.addWidget(self.frame_9, 2, 0, 1, 2)
        self.frame_6 = QtGui.QFrame(self.tabConfigurationOption)
        self.frame_6.setMinimumSize(QtCore.QSize(720, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(720, 16777215))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_35 = QtGui.QLabel(self.frame_6)
        self.label_35.setMaximumSize(QtCore.QSize(10, 27))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_7.addWidget(self.label_35, 9, 2, 1, 1)
        self.checkBoxRelativePath = QtGui.QCheckBox(self.frame_6)
        self.checkBoxRelativePath.setObjectName(_fromUtf8("checkBoxRelativePath"))
        self.gridLayout_7.addWidget(self.checkBoxRelativePath, 15, 0, 1, 8)
        self.label_33 = QtGui.QLabel(self.frame_6)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_7.addWidget(self.label_33, 6, 0, 1, 4)
        self.label_26 = QtGui.QLabel(self.frame_6)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_7.addWidget(self.label_26, 2, 0, 1, 4)
        self.lineEditBBGCHomeDir = QtGui.QLineEdit(self.frame_6)
        self.lineEditBBGCHomeDir.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEditBBGCHomeDir.setMaximumSize(QtCore.QSize(16777215, 27))
        self.lineEditBBGCHomeDir.setObjectName(_fromUtf8("lineEditBBGCHomeDir"))
        self.gridLayout_7.addWidget(self.lineEditBBGCHomeDir, 0, 5, 1, 6)
        self.label_30 = QtGui.QLabel(self.frame_6)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_7.addWidget(self.label_30, 4, 0, 1, 4)
        self.label_12 = QtGui.QLabel(self.frame_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_7.addWidget(self.label_12, 0, 0, 1, 4)
        self.checkBoxSaveStatistics = QtGui.QCheckBox(self.frame_6)
        self.checkBoxSaveStatistics.setObjectName(_fromUtf8("checkBoxSaveStatistics"))
        self.gridLayout_7.addWidget(self.checkBoxSaveStatistics, 5, 0, 1, 11)
        self.lineEditSequence = QtGui.QLineEdit(self.frame_6)
        self.lineEditSequence.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEditSequence.setMaximumSize(QtCore.QSize(16777215, 27))
        self.lineEditSequence.setObjectName(_fromUtf8("lineEditSequence"))
        self.gridLayout_7.addWidget(self.lineEditSequence, 14, 5, 1, 5)
        self.label_24 = QtGui.QLabel(self.frame_6)
        self.label_24.setMaximumSize(QtCore.QSize(10, 27))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_7.addWidget(self.label_24, 1, 4, 1, 1)
        self.comboBoxObjectiveFunction = QtGui.QComboBox(self.frame_6)
        self.comboBoxObjectiveFunction.setObjectName(_fromUtf8("comboBoxObjectiveFunction"))
        self.gridLayout_7.addWidget(self.comboBoxObjectiveFunction, 8, 7, 1, 5)
        self.lineEditConfigComparisonMapFile = QtGui.QLineEdit(self.frame_6)
        self.lineEditConfigComparisonMapFile.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEditConfigComparisonMapFile.setMaximumSize(QtCore.QSize(16777215, 27))
        self.lineEditConfigComparisonMapFile.setObjectName(_fromUtf8("lineEditConfigComparisonMapFile"))
        self.gridLayout_7.addWidget(self.lineEditConfigComparisonMapFile, 3, 5, 1, 6)
        self.label_23 = QtGui.QLabel(self.frame_6)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_7.addWidget(self.label_23, 1, 0, 1, 4)
        self.pushButtonSelectParameterMapFile = QtGui.QPushButton(self.frame_6)
        self.pushButtonSelectParameterMapFile.setMinimumSize(QtCore.QSize(30, 27))
        self.pushButtonSelectParameterMapFile.setMaximumSize(QtCore.QSize(30, 27))
        self.pushButtonSelectParameterMapFile.setObjectName(_fromUtf8("pushButtonSelectParameterMapFile"))
        self.gridLayout_7.addWidget(self.pushButtonSelectParameterMapFile, 2, 11, 1, 1)
        self.comboBoxNormalizationOption = QtGui.QComboBox(self.frame_6)
        self.comboBoxNormalizationOption.setObjectName(_fromUtf8("comboBoxNormalizationOption"))
        self.gridLayout_7.addWidget(self.comboBoxNormalizationOption, 7, 7, 1, 5)
        self.label_25 = QtGui.QLabel(self.frame_6)
        self.label_25.setMaximumSize(QtCore.QSize(10, 27))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_7.addWidget(self.label_25, 2, 4, 1, 1)
        self.buttonSelectSequenceFromParamFile = QtGui.QPushButton(self.frame_6)
        self.buttonSelectSequenceFromParamFile.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonSelectSequenceFromParamFile.setObjectName(_fromUtf8("buttonSelectSequenceFromParamFile"))
        self.gridLayout_7.addWidget(self.buttonSelectSequenceFromParamFile, 14, 3, 1, 2)
        self.label_42 = QtGui.QLabel(self.frame_6)
        self.label_42.setMaximumSize(QtCore.QSize(10, 27))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_7.addWidget(self.label_42, 12, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.frame_6)
        self.label_20.setMaximumSize(QtCore.QSize(10, 27))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_7.addWidget(self.label_20, 0, 4, 1, 1)
        self.lineEditPenaltyConstant = QtGui.QLineEdit(self.frame_6)
        self.lineEditPenaltyConstant.setObjectName(_fromUtf8("lineEditPenaltyConstant"))
        self.gridLayout_7.addWidget(self.lineEditPenaltyConstant, 12, 10, 1, 2)
        self.label_27 = QtGui.QLabel(self.frame_6)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_7.addWidget(self.label_27, 3, 0, 1, 4)
        self.label_37 = QtGui.QLabel(self.frame_6)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_7.addWidget(self.label_37, 9, 0, 1, 2)
        self.pushButtonSelectInitialFile = QtGui.QPushButton(self.frame_6)
        self.pushButtonSelectInitialFile.setMinimumSize(QtCore.QSize(30, 27))
        self.pushButtonSelectInitialFile.setMaximumSize(QtCore.QSize(30, 27))
        self.pushButtonSelectInitialFile.setObjectName(_fromUtf8("pushButtonSelectInitialFile"))
        self.gridLayout_7.addWidget(self.pushButtonSelectInitialFile, 1, 11, 1, 1)
        self.label_28 = QtGui.QLabel(self.frame_6)
        self.label_28.setMaximumSize(QtCore.QSize(10, 27))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_7.addWidget(self.label_28, 3, 4, 1, 1)
        self.buttonBGCHomeDir = QtGui.QPushButton(self.frame_6)
        self.buttonBGCHomeDir.setMinimumSize(QtCore.QSize(30, 27))
        self.buttonBGCHomeDir.setMaximumSize(QtCore.QSize(30, 27))
        self.buttonBGCHomeDir.setObjectName(_fromUtf8("buttonBGCHomeDir"))
        self.gridLayout_7.addWidget(self.buttonBGCHomeDir, 0, 11, 1, 1)
        self.comboBoxObjectiveTarget = QtGui.QComboBox(self.frame_6)
        self.comboBoxObjectiveTarget.setObjectName(_fromUtf8("comboBoxObjectiveTarget"))
        self.gridLayout_7.addWidget(self.comboBoxObjectiveTarget, 9, 3, 1, 5)
        self.lineEditConfigInitializationFile = QtGui.QLineEdit(self.frame_6)
        self.lineEditConfigInitializationFile.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEditConfigInitializationFile.setMaximumSize(QtCore.QSize(16777215, 27))
        self.lineEditConfigInitializationFile.setObjectName(_fromUtf8("lineEditConfigInitializationFile"))
        self.gridLayout_7.addWidget(self.lineEditConfigInitializationFile, 1, 5, 1, 6)
        self.checkBoxNormalizeData = QtGui.QCheckBox(self.frame_6)
        self.checkBoxNormalizeData.setObjectName(_fromUtf8("checkBoxNormalizeData"))
        self.gridLayout_7.addWidget(self.checkBoxNormalizeData, 7, 0, 1, 5)
        self.label_43 = QtGui.QLabel(self.frame_6)
        self.label_43.setMaximumSize(QtCore.QSize(10, 27))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_7.addWidget(self.label_43, 13, 2, 1, 1)
        self.checkBoxUseGlobalObjFun = QtGui.QCheckBox(self.frame_6)
        self.checkBoxUseGlobalObjFun.setMinimumSize(QtCore.QSize(210, 0))
        self.checkBoxUseGlobalObjFun.setObjectName(_fromUtf8("checkBoxUseGlobalObjFun"))
        self.gridLayout_7.addWidget(self.checkBoxUseGlobalObjFun, 8, 0, 1, 2)
        self.checkBoxUsePenaltyFun = QtGui.QCheckBox(self.frame_6)
        self.checkBoxUsePenaltyFun.setObjectName(_fromUtf8("checkBoxUsePenaltyFun"))
        self.gridLayout_7.addWidget(self.checkBoxUsePenaltyFun, 10, 0, 2, 12)
        self.pushButtonSelectComparisonMapFile = QtGui.QPushButton(self.frame_6)
        self.pushButtonSelectComparisonMapFile.setMinimumSize(QtCore.QSize(30, 27))
        self.pushButtonSelectComparisonMapFile.setMaximumSize(QtCore.QSize(30, 27))
        self.pushButtonSelectComparisonMapFile.setObjectName(_fromUtf8("pushButtonSelectComparisonMapFile"))
        self.gridLayout_7.addWidget(self.pushButtonSelectComparisonMapFile, 3, 11, 1, 1)
        self.label_29 = QtGui.QLabel(self.frame_6)
        self.label_29.setMaximumSize(QtCore.QSize(10, 27))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_7.addWidget(self.label_29, 4, 4, 1, 1)
        self.lineEditConfigParameterFile = QtGui.QLineEdit(self.frame_6)
        self.lineEditConfigParameterFile.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEditConfigParameterFile.setMaximumSize(QtCore.QSize(16777215, 27))
        self.lineEditConfigParameterFile.setObjectName(_fromUtf8("lineEditConfigParameterFile"))
        self.gridLayout_7.addWidget(self.lineEditConfigParameterFile, 2, 5, 1, 6)
        self.label_34 = QtGui.QLabel(self.frame_6)
        self.label_34.setMaximumSize(QtCore.QSize(10, 27))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_7.addWidget(self.label_34, 6, 4, 1, 1)
        self.label_38 = QtGui.QLabel(self.frame_6)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_7.addWidget(self.label_38, 8, 5, 1, 2)
        self.label_19 = QtGui.QLabel(self.frame_6)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_7.addWidget(self.label_19, 13, 0, 1, 2)
        self.label_31 = QtGui.QLabel(self.frame_6)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_7.addWidget(self.label_31, 18, 0, 1, 12)
        self.lineEditStatFileName = QtGui.QLineEdit(self.frame_6)
        self.lineEditStatFileName.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEditStatFileName.setMaximumSize(QtCore.QSize(16777215, 27))
        self.lineEditStatFileName.setObjectName(_fromUtf8("lineEditStatFileName"))
        self.gridLayout_7.addWidget(self.lineEditStatFileName, 6, 5, 1, 6)
        self.comboBoxPenaltyFunction = QtGui.QComboBox(self.frame_6)
        self.comboBoxPenaltyFunction.setObjectName(_fromUtf8("comboBoxPenaltyFunction"))
        self.gridLayout_7.addWidget(self.comboBoxPenaltyFunction, 12, 3, 1, 5)
        self.pushButtonSelectStatisticFile = QtGui.QPushButton(self.frame_6)
        self.pushButtonSelectStatisticFile.setMinimumSize(QtCore.QSize(30, 27))
        self.pushButtonSelectStatisticFile.setMaximumSize(QtCore.QSize(30, 27))
        self.pushButtonSelectStatisticFile.setObjectName(_fromUtf8("pushButtonSelectStatisticFile"))
        self.gridLayout_7.addWidget(self.pushButtonSelectStatisticFile, 6, 11, 1, 1)
        self.lineEditFileExtensionPostFix = QtGui.QLineEdit(self.frame_6)
        self.lineEditFileExtensionPostFix.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEditFileExtensionPostFix.setMaximumSize(QtCore.QSize(16777215, 27))
        self.lineEditFileExtensionPostFix.setObjectName(_fromUtf8("lineEditFileExtensionPostFix"))
        self.gridLayout_7.addWidget(self.lineEditFileExtensionPostFix, 4, 5, 1, 2)
        self.label_36 = QtGui.QLabel(self.frame_6)
        self.label_36.setMinimumSize(QtCore.QSize(210, 0))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_7.addWidget(self.label_36, 12, 0, 1, 2)
        self.label_40 = QtGui.QLabel(self.frame_6)
        self.label_40.setMinimumSize(QtCore.QSize(120, 0))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_7.addWidget(self.label_40, 12, 8, 1, 2)
        self.comboBoxParamSequenceOption = QtGui.QComboBox(self.frame_6)
        self.comboBoxParamSequenceOption.setObjectName(_fromUtf8("comboBoxParamSequenceOption"))
        self.gridLayout_7.addWidget(self.comboBoxParamSequenceOption, 13, 3, 1, 5)
        self.frameReferenceDirectory = QtGui.QFrame(self.frame_6)
        self.frameReferenceDirectory.setMinimumSize(QtCore.QSize(0, 40))
        self.frameReferenceDirectory.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameReferenceDirectory.setFrameShadow(QtGui.QFrame.Raised)
        self.frameReferenceDirectory.setObjectName(_fromUtf8("frameReferenceDirectory"))
        self.gridLayout_11 = QtGui.QGridLayout(self.frameReferenceDirectory)
        self.gridLayout_11.setContentsMargins(9, 0, -1, 0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.radioButtonDefaultHPDirectory = QtGui.QRadioButton(self.frameReferenceDirectory)
        self.radioButtonDefaultHPDirectory.setMinimumSize(QtCore.QSize(260, 27))
        self.radioButtonDefaultHPDirectory.setChecked(True)
        self.radioButtonDefaultHPDirectory.setObjectName(_fromUtf8("radioButtonDefaultHPDirectory"))
        self.gridLayout_11.addWidget(self.radioButtonDefaultHPDirectory, 0, 0, 1, 1)
        self.radioButtonSetHPDirectory = QtGui.QRadioButton(self.frameReferenceDirectory)
        self.radioButtonSetHPDirectory.setMinimumSize(QtCore.QSize(270, 27))
        self.radioButtonSetHPDirectory.setObjectName(_fromUtf8("radioButtonSetHPDirectory"))
        self.gridLayout_11.addWidget(self.radioButtonSetHPDirectory, 0, 1, 1, 2)
        self.pushButtonRefDirectory = QtGui.QPushButton(self.frameReferenceDirectory)
        self.pushButtonRefDirectory.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButtonRefDirectory.setObjectName(_fromUtf8("pushButtonRefDirectory"))
        self.gridLayout_11.addWidget(self.pushButtonRefDirectory, 0, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.frameReferenceDirectory)
        self.label_32.setMinimumSize(QtCore.QSize(160, 0))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_11.addWidget(self.label_32, 1, 0, 1, 1)
        self.label_44 = QtGui.QLabel(self.frameReferenceDirectory)
        self.label_44.setMinimumSize(QtCore.QSize(10, 0))
        self.label_44.setMaximumSize(QtCore.QSize(10, 27))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_11.addWidget(self.label_44, 1, 1, 1, 1)
        self.labelReferenceDirectory = QtGui.QLabel(self.frameReferenceDirectory)
        self.labelReferenceDirectory.setMinimumSize(QtCore.QSize(200, 0))
        self.labelReferenceDirectory.setObjectName(_fromUtf8("labelReferenceDirectory"))
        self.gridLayout_11.addWidget(self.labelReferenceDirectory, 1, 2, 1, 2)
        self.gridLayout_7.addWidget(self.frameReferenceDirectory, 16, 0, 2, 12)
        self.gridLayout_9.addWidget(self.frame_6, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabConfigurationOption, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(FormEvaluatorConfiguration)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormEvaluatorConfiguration)

    def retranslateUi(self, FormEvaluatorConfiguration):
        FormEvaluatorConfiguration.setWindowTitle(_translate("FormEvaluatorConfiguration", "Evaluator Configuration", None))
        self.buttonSave.setText(_translate("FormEvaluatorConfiguration", "Save", None))
        self.buttonClose.setText(_translate("FormEvaluatorConfiguration", "Close", None))
        self.labelNotes.setText(_translate("FormEvaluatorConfiguration", "TextLabel", None))
        self.buttonLoadFromFile.setText(_translate("FormEvaluatorConfiguration", "Load from File", None))
        self.buttonAddToList.setText(_translate("FormEvaluatorConfiguration", "Add to List", None))
        self.label_13.setText(_translate("FormEvaluatorConfiguration", "List of Selected Parameter(s):", None))
        self.checkBoxSpecifyIndex.setText(_translate("FormEvaluatorConfiguration", "Specify Parameter Indices from Initialization File", None))
        self.pushButtonInitialFile.setText(_translate("FormEvaluatorConfiguration", "...", None))
        self.label_4.setText(_translate("FormEvaluatorConfiguration", "Parameter Type :", None))
        self.checkBoxPreferred.setText(_translate("FormEvaluatorConfiguration", "Use preferred and hard bounds", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabParameterSelection), _translate("FormEvaluatorConfiguration", "Parameter Selection", None))
        self.buttonAddComparisonOption.setText(_translate("FormEvaluatorConfiguration", "Add", None))
        self.buttonLoad.setText(_translate("FormEvaluatorConfiguration", "Load", None))
        self.labelObservationDataFile.setText(_translate("FormEvaluatorConfiguration", "Observation file (CSV):", None))
        self.label_22.setText(_translate("FormEvaluatorConfiguration", ":", None))
        self.buttonMeasuredDataFile.setText(_translate("FormEvaluatorConfiguration", "...", None))
        self.label_2.setText(_translate("FormEvaluatorConfiguration", "Output File Type", None))
        self.label.setText(_translate("FormEvaluatorConfiguration", "Model Initialization File:", None))
        self.buttonInitializationFile.setText(_translate("FormEvaluatorConfiguration", "...", None))
        self.label_3.setText(_translate("FormEvaluatorConfiguration", "Observation Type", None))
        self.label_21.setText(_translate("FormEvaluatorConfiguration", ":", None))
        self.label_15.setText(_translate("FormEvaluatorConfiguration", ":", None))
        self.buttonModelOutputVariable.setText(_translate("FormEvaluatorConfiguration", ">", None))
        self.label_16.setText(_translate("FormEvaluatorConfiguration", ":", None))
        self.buttonModelPairingVariable.setText(_translate("FormEvaluatorConfiguration", ">", None))
        self.buttonMeasuredPairingVariable.setText(_translate("FormEvaluatorConfiguration", ">", None))
        self.label_8.setText(_translate("FormEvaluatorConfiguration", "Pairing Variable (Model)", None))
        self.label_7.setText(_translate("FormEvaluatorConfiguration", "Pairing Variable (Obs.)", None))
        self.label_11.setText(_translate("FormEvaluatorConfiguration", "Weighting Factor", None))
        self.buttonMeasuredVariable.setText(_translate("FormEvaluatorConfiguration", ">", None))
        self.label_17.setText(_translate("FormEvaluatorConfiguration", ":", None))
        self.label_9.setText(_translate("FormEvaluatorConfiguration", "Coversion Factor (Model)", None))
        self.checkBoxOverrideObjFun.setText(_translate("FormEvaluatorConfiguration", "Override Objective Function", None))
        self.label_18.setText(_translate("FormEvaluatorConfiguration", ":", None))
        self.label_10.setText(_translate("FormEvaluatorConfiguration", "Coversion Factor (Obs)", None))
        self.label_14.setText(_translate("FormEvaluatorConfiguration", "Group Name:", None))
        self.label_5.setText(_translate("FormEvaluatorConfiguration", "(Model) Predicted Variable", None))
        self.label_6.setText(_translate("FormEvaluatorConfiguration", "Observation Variable", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabComparisonOption), _translate("FormEvaluatorConfiguration", "Prediction-Observation Variable", None))
        self.radioButtonCreateConfigFile.setText(_translate("FormEvaluatorConfiguration", "Create Config-file", None))
        self.radioButtonUpdateConfigFile.setText(_translate("FormEvaluatorConfiguration", "Update Config-file", None))
        self.buttonChooseConfigFile.setText(_translate("FormEvaluatorConfiguration", "Select Config-File", None))
        self.labelSelectedConfigFile.setText(_translate("FormEvaluatorConfiguration", "(selected config-file)", None))
        self.label_35.setText(_translate("FormEvaluatorConfiguration", ":", None))
        self.checkBoxRelativePath.setText(_translate("FormEvaluatorConfiguration", "Use relative path from HOPSPACK home directory", None))
        self.label_33.setText(_translate("FormEvaluatorConfiguration", "Statistics Filename", None))
        self.label_26.setText(_translate("FormEvaluatorConfiguration", "Parameter Map File *", None))
        self.label_30.setText(_translate("FormEvaluatorConfiguration", "File-extension Postfix for temp files *", None))
        self.label_12.setText(_translate("FormEvaluatorConfiguration", "Biome BGC Model Home Directory *", None))
        self.checkBoxSaveStatistics.setText(_translate("FormEvaluatorConfiguration", "Save Intermediate Parameter Values and Statistics (fit of prediction and observation)", None))
        self.label_24.setText(_translate("FormEvaluatorConfiguration", ":", None))
        self.label_23.setText(_translate("FormEvaluatorConfiguration", "Model Initialization Filename *", None))
        self.pushButtonSelectParameterMapFile.setText(_translate("FormEvaluatorConfiguration", "....", None))
        self.label_25.setText(_translate("FormEvaluatorConfiguration", ":", None))
        self.buttonSelectSequenceFromParamFile.setText(_translate("FormEvaluatorConfiguration", "Select", None))
        self.label_42.setText(_translate("FormEvaluatorConfiguration", ":", None))
        self.label_20.setText(_translate("FormEvaluatorConfiguration", ":", None))
        self.label_27.setText(_translate("FormEvaluatorConfiguration", "Comparison Variable-Map File *", None))
        self.label_37.setText(_translate("FormEvaluatorConfiguration", "Objective Target *", None))
        self.pushButtonSelectInitialFile.setText(_translate("FormEvaluatorConfiguration", "....", None))
        self.label_28.setText(_translate("FormEvaluatorConfiguration", ":", None))
        self.buttonBGCHomeDir.setText(_translate("FormEvaluatorConfiguration", "....", None))
        self.checkBoxNormalizeData.setText(_translate("FormEvaluatorConfiguration", "Normalize Predictions and Observation", None))
        self.label_43.setText(_translate("FormEvaluatorConfiguration", ":", None))
        self.checkBoxUseGlobalObjFun.setText(_translate("FormEvaluatorConfiguration", "Use Global Objective Function ", None))
        self.checkBoxUsePenaltyFun.setText(_translate("FormEvaluatorConfiguration", "Use penalty function for parameter values outside preferred zone", None))
        self.pushButtonSelectComparisonMapFile.setText(_translate("FormEvaluatorConfiguration", "....", None))
        self.label_29.setText(_translate("FormEvaluatorConfiguration", ":", None))
        self.label_34.setText(_translate("FormEvaluatorConfiguration", ":", None))
        self.label_38.setText(_translate("FormEvaluatorConfiguration", "Objective Function  :", None))
        self.label_19.setText(_translate("FormEvaluatorConfiguration", "Parameter Sequence *", None))
        self.label_31.setText(_translate("FormEvaluatorConfiguration", "[Note: Mandatory fields are marked with *]", None))
        self.pushButtonSelectStatisticFile.setText(_translate("FormEvaluatorConfiguration", "....", None))
        self.label_36.setText(_translate("FormEvaluatorConfiguration", "Penalty Function", None))
        self.label_40.setText(_translate("FormEvaluatorConfiguration", "Penalty  Constant  :", None))
        self.radioButtonDefaultHPDirectory.setText(_translate("FormEvaluatorConfiguration", "Use Defaulf Hopspack Home Directory", None))
        self.radioButtonSetHPDirectory.setText(_translate("FormEvaluatorConfiguration", "Set a directory as Hopspack home directory", None))
        self.pushButtonRefDirectory.setText(_translate("FormEvaluatorConfiguration", "Set Ref. Directory", None))
        self.label_32.setText(_translate("FormEvaluatorConfiguration", "Reference Directory (HOPSPACK Home)", None))
        self.label_44.setText(_translate("FormEvaluatorConfiguration", ":", None))
        self.labelReferenceDirectory.setText(_translate("FormEvaluatorConfiguration", "/hopspack/", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConfigurationOption), _translate("FormEvaluatorConfiguration", "Configuration Option", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    FormEvaluatorConfiguration = QtWidgets.QWidget()
    ui = Ui_FormEvaluatorConfiguration()
    ui.setupUi(FormEvaluatorConfiguration)
    FormEvaluatorConfiguration.show()
    sys.exit(app.exec_())

