# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormHopspackRun.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormHopspackRun(object):
    def setupUi(self, FormHopspackRun):
        FormHopspackRun.setObjectName("FormHopspackRun")
        FormHopspackRun.resize(421, 179)
        self.gridLayout_2 = QtWidgets.QGridLayout(FormHopspackRun)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(FormHopspackRun)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_5 = QtWidgets.QWidget(self.frame)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.widget_5)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEditInitialFile = QtWidgets.QLineEdit(self.widget)
        self.lineEditInitialFile.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditInitialFile.setReadOnly(True)
        self.lineEditInitialFile.setObjectName("lineEditInitialFile")
        self.gridLayout_3.addWidget(self.lineEditInitialFile, 0, 1, 1, 1)
        self.buttonBrowseInitialFile = QtWidgets.QPushButton(self.widget)
        self.buttonBrowseInitialFile.setMaximumSize(QtCore.QSize(40, 16777215))
        self.buttonBrowseInitialFile.setObjectName("buttonBrowseInitialFile")
        self.gridLayout_3.addWidget(self.buttonBrowseInitialFile, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditModelExecutable = QtWidgets.QLineEdit(self.widget)
        self.lineEditModelExecutable.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditModelExecutable.setReadOnly(True)
        self.lineEditModelExecutable.setObjectName("lineEditModelExecutable")
        self.gridLayout_3.addWidget(self.lineEditModelExecutable, 1, 1, 1, 1)
        self.buttonBrowseModelExecutable = QtWidgets.QPushButton(self.widget)
        self.buttonBrowseModelExecutable.setMaximumSize(QtCore.QSize(40, 16777215))
        self.buttonBrowseModelExecutable.setObjectName("buttonBrowseModelExecutable")
        self.gridLayout_3.addWidget(self.buttonBrowseModelExecutable, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.widget_5)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.buttonRun = QtWidgets.QPushButton(self.widget_3)
        self.buttonRun.setObjectName("buttonRun")
        self.horizontalLayout_2.addWidget(self.buttonRun)
        self.buttonClose = QtWidgets.QPushButton(self.widget_3)
        self.buttonClose.setObjectName("buttonClose")
        self.horizontalLayout_2.addWidget(self.buttonClose)
        self.horizontalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.gridLayout.addWidget(self.widget_5, 0, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.frame)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout.addWidget(self.widget_6, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 5)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.widget_8 = QtWidgets.QWidget(FormHopspackRun)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_2.addWidget(self.widget_8, 0, 1, 1, 1)
        self.widget_7 = QtWidgets.QWidget(FormHopspackRun)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_2.addWidget(self.widget_7, 1, 0, 1, 2)
        self.gridLayout_2.setColumnStretch(1, 5)
        self.gridLayout_2.setRowStretch(1, 5)

        self.retranslateUi(FormHopspackRun)
        QtCore.QMetaObject.connectSlotsByName(FormHopspackRun)

    def retranslateUi(self, FormHopspackRun):
        _translate = QtCore.QCoreApplication.translate
        FormHopspackRun.setWindowTitle(_translate("FormHopspackRun", "Run - HOPSPACK"))
        self.buttonBrowseInitialFile.setText(_translate("FormHopspackRun", "..."))
        self.label.setText(_translate("FormHopspackRun", "Model Initial File :"))
        self.label_2.setText(_translate("FormHopspackRun", "Model Executable :"))
        self.buttonBrowseModelExecutable.setText(_translate("FormHopspackRun", "..."))
        self.buttonRun.setText(_translate("FormHopspackRun", "Run"))
        self.buttonClose.setText(_translate("FormHopspackRun", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormHopspackRun = QtWidgets.QWidget()
    ui = Ui_FormHopspackRun()
    ui.setupUi(FormHopspackRun)
    FormHopspackRun.show()
    sys.exit(app.exec_())
